/* based on ORSCF VisitData Contract v1.7.0.0 */


export class VisitFilter {
  
  public studyUid?: string;
  
  public siteUid?: string;
  
  /**
   * identity of the patient which is usually a pseudonym from a corr. 'IdentiyManagementSystem' (the exact semantic is defined per study) *this field has a max length of 100
   */
  public subjectIdentifier?: string;
  
  public visitProcedureName?: string;
  
  /**
   * unique title of the visit execution as defined in the 'StudyWorkflowDefinition' (originated from the sponsor)
   */
  public visitExecutionTitle: string = '';
  
  /**
   * 0=Unscheduled / 1=Sheduled / 2=Executed / 3=AbortDuringExecution / 4=Skipped / 5=Removed
   */
  public executionState?: number;
  
  public minScheduledDateUtc?: Date;
  
  public maxScheduledDateUtc?: Date;
  
  public minExecutionDateUtc?: Date;
  
  public maxExecutionDateUtc?: Date;
  
  /**
   * Custom fields as defined by the Service. Call 'GetCustomFieldDescriptors' to get information about supported/required fields. Any passed values for undefined fields will be ignored.
   */
  public customFields?: Object;
  
}

export class VisitMetaRecord {
  
  /**
   * An [Universally Unique Identifier](https://de.wikipedia.org/wiki/Universally_Unique_Identifier) which can be generated by any origin system and is used to address this ORSCF conform data record in decentralized environments. Note that this Identity must not be changed any more!
   */
  public visitUid: string = '';
  
  public studyUid: string = '';
  
  public siteUid: string = '';
  
  /**
   * identity of the patient which is usually a pseudonym from a corr. 'IdentiyManagementSystem' (the exact semantic is defined per study) *this field has a max length of 100
   */
  public subjectIdentifier: string = '';
  
  /**
   * This is an internal managed field, which is related to the state of records dedicated to the database. It will be automatically set when a record is archived. A mapping during data import requires opt-in.
   */
  public isArchived: boolean = false;
  
  /**
   * This is an internal managed field (UNIX-Timestamp), which is related to the state of records dedicated to the database. It will be automatically set to the current time when a record is created, updated, archived or unarchived, but cannot be updated from outside and must not be mapped during data imports.
   */
  public modificationTimestampUtc: number = 0;
  
}

export class DataRecordingMetaRecord {
  
  /**
   * An [Universally Unique Identifier](https://de.wikipedia.org/wiki/Universally_Unique_Identifier) which can be generated by any origin system and is used to address this ORSCF conform data record in decentralized environments. Note that this Identity must not be changed any more!
   */
  public dataRecordingUid: string = '';
  
  public visitUid: string = '';
  
  /**
   * This is an internal managed field, which is related to the state of records dedicated to the database. It will be automatically set when a record is archived. A mapping during data import requires opt-in.
   */
  public isArchived: boolean = false;
  
  /**
   * This is an internal managed field (UNIX-Timestamp), which is related to the state of records dedicated to the database. It will be automatically set to the current time when a record is created, updated, archived or unarchived, but cannot be updated from outside and must not be mapped during data imports.
   */
  public modificationTimestampUtc: number = 0;
  
}

export class CustomFieldDescriptor {
  
  public technicalName: string = '';
  
  public isRequired: boolean = false;
  
  public displayLabel: string = '';
  
  public inputDescription?: string;
  
  public defaultValue?: string;
  
  public presets?: string[];
  
  public presetsOnly?: boolean;
  
  public regularExpression?: string;
  
}

export class VisitFields extends VisitMetaRecord {
  
  /**
   * unique invariant name of the visit-procedure as defined in the 'StudyWorkflowDefinition' (originated from the sponsor)
   */
  public visitProcedureName: string = '';
  
  /**
   * unique title of the visit execution as defined in the 'StudyWorkflowDefinition' (originated from the sponsor)
   */
  public visitExecutionTitle: string = '';
  
  /**
   * the estimated date when the visit is scheduled for execution *this field is optional
   */
  public scheduledDateUtc?: Date;
  
  /**
   * the real date, when the visits was executed *this field is optional
   */
  public executionDateUtc?: Date;
  
  /**
   * 0=Unscheduled / 1=Sheduled / 2=Executed / 3=AbortDuringExecution / 4=Skipped / 5=Removed
   */
  public executionState: number = 0;
  
  /**
   * *this field is optional (use null as value)
   */
  public executingPerson?: string;
  
  /**
   * Custom fields as defined by the Service. Call 'GetCustomFieldDescriptors' to get information about supported/required fields. Any passed values for undefined fields will be ignored.
   */
  public customFields?: Object;
  
  /**
   * An [Universally Unique Identifier](https://de.wikipedia.org/wiki/Universally_Unique_Identifier) which can be generated by any origin system and is used to address this ORSCF conform data record in decentralized environments. Note that this Identity must not be changed any more!
   */
  public visitUid: string = '';
  
  public studyUid: string = '';
  
  public siteUid: string = '';
  
  /**
   * identity of the patient which is usually a pseudonym from a corr. 'IdentiyManagementSystem' (the exact semantic is defined per study) *this field has a max length of 100
   */
  public subjectIdentifier: string = '';
  
  /**
   * This is an internal managed field, which is related to the state of records dedicated to the database. It will be automatically set when a record is archived. A mapping during data import requires opt-in.
   */
  public isArchived: boolean = false;
  
  /**
   * This is an internal managed field (UNIX-Timestamp), which is related to the state of records dedicated to the database. It will be automatically set to the current time when a record is created, updated, archived or unarchived, but cannot be updated from outside and must not be mapped during data imports.
   */
  public modificationTimestampUtc: number = 0;
  
}

/**
 * A structure containing HL7/FHIR-Ressources (JSON only) and the essential fields which are required to qualify a ORSCF record.
 */
export class VisitFhirRessourceContainer extends VisitMetaRecord {
  
  /**
   * a HL7 ['Appointment'](http://www.hl7.org/fhir/appointment.html) resource in json format
   */
  public appointmentRessource?: Object;
  
  /**
   * An [Universally Unique Identifier](https://de.wikipedia.org/wiki/Universally_Unique_Identifier) which can be generated by any origin system and is used to address this ORSCF conform data record in decentralized environments. Note that this Identity must not be changed any more!
   */
  public visitUid: string = '';
  
  public studyUid: string = '';
  
  public siteUid: string = '';
  
  /**
   * identity of the patient which is usually a pseudonym from a corr. 'IdentiyManagementSystem' (the exact semantic is defined per study) *this field has a max length of 100
   */
  public subjectIdentifier: string = '';
  
  /**
   * This is an internal managed field, which is related to the state of records dedicated to the database. It will be automatically set when a record is archived. A mapping during data import requires opt-in.
   */
  public isArchived: boolean = false;
  
  /**
   * This is an internal managed field (UNIX-Timestamp), which is related to the state of records dedicated to the database. It will be automatically set to the current time when a record is created, updated, archived or unarchived, but cannot be updated from outside and must not be mapped during data imports.
   */
  public modificationTimestampUtc: number = 0;
  
}

export class BatchableVisitMutation {
  
  /**
   * unique invariant name of the visit-procedure as defined in the 'StudyWorkflowDefinition' (originated from the sponsor)
   */
  public visitProcedureName?: string;
  
  /**
   * unique title of the visit execution as defined in the 'StudyWorkflowDefinition' (originated from the sponsor)
   */
  public visitExecutionTitle?: string;
  
  /**
   * 0=Unscheduled / 1=Sheduled / 2=Executed / 3=AbortDuringExecution / 4=Skipped / 5=Removed
   */
  public executionState?: number;
  
  /**
   * *this field is optional (use null as value)
   */
  public executingPerson?: string;
  
  /**
   * Custom fields as defined by the Service. Call 'GetCustomFieldDescriptors' to get information about supported/required fields. Any passed values for undefined fields will be ignored.
   */
  public customFields?: Object;
  
}

export class DataRecordingFields extends DataRecordingMetaRecord {
  
  /**
   * unique invariant name of ths task-procedure as defined in the 'StudyWorkflowDefinition' (originated from the sponsor)
   */
  public dataRecordingName: string = '';
  
  /**
   * title of the task execution as defined in the 'StudyWorkflowDefinition' (originated from the sponsor)
   */
  public taskExecutionTitle: string = '';
  
  /**
   * the estimated date when the visit is scheduled *this field is optional
   */
  public scheduledDateTimeUtc?: Date;
  
  /**
   * the real time, when the data was recorded *this field is optional
   */
  public executionDateTimeUtc?: Date;
  
  /**
   * 0=Unscheduled / 1=Sheduled / 2=Executed / 3=AbortDuringExecution / 4=Skipped / 5=Removed
   */
  public executionState: number = 0;
  
  /**
   * schema-url of the data which were stored inside of the 'RecordedData' field
   */
  public dataSchemaUrl: string = '';
  
  /**
   * version of schema, which is addressed by the 'DataSchemaUrl'
   */
  public dataSchemaVersion: string = '';
  
  /**
   * 'FhirQuestionaire' / 'XML' / 'CSV' / 'Custom'
   */
  public dataSchemaKind: string = '';
  
  /**
   * Language of free-text information inside of the data content
   */
  public dataLanguage?: string;
  
  /**
   * additional notes regarding this dedcated execution (supplied by the execution person) *this field is optional (use null as value)
   */
  public notesRegardingOutcome?: string;
  
  /**
   * *this field is optional (use null as value)
   */
  public executingPerson?: string;
  
  /**
   * Custom fields as defined by the Service. Call 'GetCustomFieldDescriptors' to get information about supported/required fields. Any passed values for undefined fields will be ignored.
   */
  public customFields?: Object;
  
  /**
   * An [Universally Unique Identifier](https://de.wikipedia.org/wiki/Universally_Unique_Identifier) which can be generated by any origin system and is used to address this ORSCF conform data record in decentralized environments. Note that this Identity must not be changed any more!
   */
  public dataRecordingUid: string = '';
  
  public visitUid: string = '';
  
  /**
   * This is an internal managed field, which is related to the state of records dedicated to the database. It will be automatically set when a record is archived. A mapping during data import requires opt-in.
   */
  public isArchived: boolean = false;
  
  /**
   * This is an internal managed field (UNIX-Timestamp), which is related to the state of records dedicated to the database. It will be automatically set to the current time when a record is created, updated, archived or unarchived, but cannot be updated from outside and must not be mapped during data imports.
   */
  public modificationTimestampUtc: number = 0;
  
}

export class VisitMutation extends BatchableVisitMutation {
  
  /**
   * the estimated date when the visit is scheduled for execution *this field is optional
   */
  public scheduledDateUtc?: Date;
  
  /**
   * the real date, when the visits was executed *this field is optional
   */
  public executionDateUtc?: Date;
  
  /**
   * unique invariant name of the visit-procedure as defined in the 'StudyWorkflowDefinition' (originated from the sponsor)
   */
  public visitProcedureName?: string;
  
  /**
   * unique title of the visit execution as defined in the 'StudyWorkflowDefinition' (originated from the sponsor)
   */
  public visitExecutionTitle?: string;
  
  /**
   * 0=Unscheduled / 1=Sheduled / 2=Executed / 3=AbortDuringExecution / 4=Skipped / 5=Removed
   */
  public executionState?: number;
  
  /**
   * *this field is optional (use null as value)
   */
  public executingPerson?: string;
  
  /**
   * Custom fields as defined by the Service. Call 'GetCustomFieldDescriptors' to get information about supported/required fields. Any passed values for undefined fields will be ignored.
   */
  public customFields?: Object;
  
}

export class DataRecordingStructure extends DataRecordingFields {
  
  /**
   * RAW data, in the schema as defined at the 'DataSchemaUrl'
   */
  public recordedData: string = '';
  
  /**
   * unique invariant name of ths task-procedure as defined in the 'StudyWorkflowDefinition' (originated from the sponsor)
   */
  public dataRecordingName: string = '';
  
  /**
   * title of the task execution as defined in the 'StudyWorkflowDefinition' (originated from the sponsor)
   */
  public taskExecutionTitle: string = '';
  
  /**
   * the estimated date when the visit is scheduled *this field is optional
   */
  public scheduledDateTimeUtc?: Date;
  
  /**
   * the real time, when the data was recorded *this field is optional
   */
  public executionDateTimeUtc?: Date;
  
  /**
   * 0=Unscheduled / 1=Sheduled / 2=Executed / 3=AbortDuringExecution / 4=Skipped / 5=Removed
   */
  public executionState: number = 0;
  
  /**
   * schema-url of the data which were stored inside of the 'RecordedData' field
   */
  public dataSchemaUrl: string = '';
  
  /**
   * version of schema, which is addressed by the 'DataSchemaUrl'
   */
  public dataSchemaVersion: string = '';
  
  /**
   * 'FhirQuestionaire' / 'XML' / 'CSV' / 'Custom'
   */
  public dataSchemaKind: string = '';
  
  /**
   * Language of free-text information inside of the data content
   */
  public dataLanguage?: string;
  
  /**
   * additional notes regarding this dedcated execution (supplied by the execution person) *this field is optional (use null as value)
   */
  public notesRegardingOutcome?: string;
  
  /**
   * *this field is optional (use null as value)
   */
  public executingPerson?: string;
  
  /**
   * Custom fields as defined by the Service. Call 'GetCustomFieldDescriptors' to get information about supported/required fields. Any passed values for undefined fields will be ignored.
   */
  public customFields?: Object;
  
  /**
   * An [Universally Unique Identifier](https://de.wikipedia.org/wiki/Universally_Unique_Identifier) which can be generated by any origin system and is used to address this ORSCF conform data record in decentralized environments. Note that this Identity must not be changed any more!
   */
  public dataRecordingUid: string = '';
  
  public visitUid: string = '';
  
  /**
   * This is an internal managed field, which is related to the state of records dedicated to the database. It will be automatically set when a record is archived. A mapping during data import requires opt-in.
   */
  public isArchived: boolean = false;
  
  /**
   * This is an internal managed field (UNIX-Timestamp), which is related to the state of records dedicated to the database. It will be automatically set to the current time when a record is created, updated, archived or unarchived, but cannot be updated from outside and must not be mapped during data imports.
   */
  public modificationTimestampUtc: number = 0;
  
}

export class VisitStructure extends VisitFields {
  
  public dataRecordings?: DataRecordingStructure[];
  
  /**
   * unique invariant name of the visit-procedure as defined in the 'StudyWorkflowDefinition' (originated from the sponsor)
   */
  public visitProcedureName: string = '';
  
  /**
   * unique title of the visit execution as defined in the 'StudyWorkflowDefinition' (originated from the sponsor)
   */
  public visitExecutionTitle: string = '';
  
  /**
   * the estimated date when the visit is scheduled for execution *this field is optional
   */
  public scheduledDateUtc?: Date;
  
  /**
   * the real date, when the visits was executed *this field is optional
   */
  public executionDateUtc?: Date;
  
  /**
   * 0=Unscheduled / 1=Sheduled / 2=Executed / 3=AbortDuringExecution / 4=Skipped / 5=Removed
   */
  public executionState: number = 0;
  
  /**
   * *this field is optional (use null as value)
   */
  public executingPerson?: string;
  
  /**
   * Custom fields as defined by the Service. Call 'GetCustomFieldDescriptors' to get information about supported/required fields. Any passed values for undefined fields will be ignored.
   */
  public customFields?: Object;
  
  /**
   * An [Universally Unique Identifier](https://de.wikipedia.org/wiki/Universally_Unique_Identifier) which can be generated by any origin system and is used to address this ORSCF conform data record in decentralized environments. Note that this Identity must not be changed any more!
   */
  public visitUid: string = '';
  
  public studyUid: string = '';
  
  public siteUid: string = '';
  
  /**
   * identity of the patient which is usually a pseudonym from a corr. 'IdentiyManagementSystem' (the exact semantic is defined per study) *this field has a max length of 100
   */
  public subjectIdentifier: string = '';
  
  /**
   * This is an internal managed field, which is related to the state of records dedicated to the database. It will be automatically set when a record is archived. A mapping during data import requires opt-in.
   */
  public isArchived: boolean = false;
  
  /**
   * This is an internal managed field (UNIX-Timestamp), which is related to the state of records dedicated to the database. It will be automatically set to the current time when a record is created, updated, archived or unarchived, but cannot be updated from outside and must not be mapped during data imports.
   */
  public modificationTimestampUtc: number = 0;
  
}
