/* based on ORSCF StudyManagement Contract v1.7.0.0 */


export class Institute {
  
  /**
   * An [Universally Unique Identifier](https://de.wikipedia.org/wiki/Universally_Unique_Identifier) which can be generated by any origin system and is used to address this ORSCF conform data record in decentralized environments. Note that this Identity must not be changed any more!
   */
  public instituteUid : string;
  
  /**
   * An DisplayLabel which is dedicated for the usage within the frontend of study managent software. Note that this short name representation hat the caracter of an internal shortcurt and could be ambiguous. The usage for legal-relevant/official communication or documents is not recommended, as well as the usage for technical identification of this record. *this field has a max length of 100
   */
  public displayLabel : string;
  
  public isArchived : boolean;
  
}

export class InstituteRelatedSystemAssignment {
  
  public instituteRelatedSystemAssignemntUid : string;
  
  public systemEndpointUid : string;
  
  public instituteUid : string;
  
  public useAsOwnPatientSdr : string;
  
  public useAsCandidateSdr : string;
  
  public useAsOwnWdr : string;
  
  public useAsConsumingExternalWdr : string;
  
  /**
   * semicolon separated list of custom role-names
   */
  public customRoles : string;
  
}

export class InvolvedPerson {
  
  /**
   * An [Universally Unique Identifier](https://de.wikipedia.org/wiki/Universally_Unique_Identifier) which can be generated by any origin system and is used to address this ORSCF conform data record in decentralized environments. Note that this Identity must not be changed any more!
   */
  public involvedPersonUid : string;
  
  /**
   * *this field is optional (use null as value)
   */
  public displayLabel : string;
  
  /**
   * *this field is optional
   */
  public emailAddress : string;
  
  public isArchived : boolean;
  
}

export class InvolvementRole {
  
  /**
   * An [Universally Unique Identifier](https://de.wikipedia.org/wiki/Universally_Unique_Identifier) which can be generated by any origin system and is used to address this ORSCF conform data record in decentralized environments. Note that this Identity must not be changed any more!
   */
  public involvedPersonRoleUid : string;
  
  public researchStudyUid : string;
  
  /**
   * *this field is optional (use null as value)
   */
  public role : string;
  
  /**
   * *this field is optional
   */
  public involvedFrom : Date;
  
  /**
   * *this field is optional
   */
  public involvedUntil : Date;
  
  /**
   * null indicated a site independent global role *this field is optional
   */
  public dedicatedToSiteUid : string;
  
  public involvedPersonUid : string;
  
}

/**
 * entity, which relates to [HL7.ResearchStudy](https://www.hl7.org/fhir/researchstudy.html)
 */
export class ResearchStudy {
  
  /**
   * An [Universally Unique Identifier](https://de.wikipedia.org/wiki/Universally_Unique_Identifier) which can be generated by any origin system and is used to address this ORSCF conform data record in decentralized environments. Note that this Identity must not be changed any more!
   */
  public researchStudyUid : string;
  
  /**
   * An DisplayLabel which is dedicated for the usage within the frontend of study managent software. Note that this short name representation hat the caracter of an internal shortcurt and could be ambiguous. The usage for legal-relevant/official communication or documents is not recommended, as well as the usage for technical identification of this record. *this field has a max length of 100
   */
  public displayLabel : string;
  
  public initiatorInstituteUid : string;
  
  public studyWorkflowName : string;
  
  public studyWorkflowVersion : string;
  
  /**
   * AS DECLARED BY [HL7.ResearchStudyPhase](https://www.hl7.org/fhir/valueset-research-study-phase.html): n-a | early-phase-1 | phase-1 | phase-1-phase-2 | phase-2 | phase-2-phase-3 | phase-3 | phase-4 *this field is optional (use null as value)
   */
  public phase : string;
  
  /**
   * a estimated date in future is possible *this field is optional
   */
  public startDate : Date;
  
  /**
   * a estimated date in future is possible *this field is optional
   */
  public terminationDate : Date;
  
  /**
   * A title which informs about the sematic of the SubjectIdentifer (which concrete value is used): "Randomization-Number", "Screening-Number", ...
   */
  public subjectIdentifierTitle : string;
  
  /**
   * AS DECLARED BY [HL7.ResearchStudyStatus](https://www.hl7.org/fhir/valueset-research-study-status.html): active | administratively-completed | approved | closed-to-accrual | closed-to-accrual-and-intervention | completed | disapproved | in-review | temporarily-closed-to-accrual | temporarily-closed-to-accrual-and-intervention | withdrawn
   */
  public status : string;
  
  /**
   * *this field is optional (use null as value)
   */
  public terminatedReason : string;
  
  public isArchived : boolean;
  
  /**
   * *this field is optional (use null as value)
   */
  public initiatorRelatedProjectNumber : string;
  
  /**
   * *this field is optional
   */
  public originWdrEndpointUid : string;
  
}

export class Site {
  
  /**
   * An [Universally Unique Identifier](https://de.wikipedia.org/wiki/Universally_Unique_Identifier) which can be generated by any origin system and is used to address this ORSCF conform data record in decentralized environments. Note that this Identity must not be changed any more!
   */
  public siteUid : string;
  
  /**
   * [Universally Unique Identifier](https://de.wikipedia.org/wiki/Universally_Unique_Identifier) of the institute, which is representing this site
   */
  public representingInstituteUid : string;
  
  /**
   * [Universally Unique Identifier](https://de.wikipedia.org/wiki/Universally_Unique_Identifier) of the related record
   */
  public researchStudyUid : string;
  
  /**
   * a estimated date in future is possible *this field is optional
   */
  public enrollmentDate : Date;
  
  /**
   * a estimated date in future is possible *this field is optional
   */
  public terminationDate : Date;
  
  /**
   * *this field is optional (use null as value)
   */
  public terminatedReason : string;
  
  /**
   * Offical 'SiteIdentifier' which is unique within the scope of the related study
   */
  public studyRelatedSiteIdentifer : string;
  
  /**
   * An DisplayLabel which is dedicated for the usage within the frontend of study managent software. Note that this short name representation hat the caracter of an internal shortcurt and could be ambiguous. The usage for legal-relevant/official communication or documents is not recommended, as well as the usage for technical identification of this record.
   */
  public displayLabel : string;
  
  /**
   * AS DECLARED BY HL7
   */
  public status : string;
  
  /**
   * *this field is optional (use null as value)
   */
  public siteRelatedProjectNumber : string;
  
}

export class SiteRelatedSystemAssignment {
  
  public siteRelatedSystemAssignmentUid : string;
  
  public systemEndpointUid : string;
  
  public siteUid : string;
  
  /**
   * semicolon separated list of custom role-names
   */
  public customRoles : string;
  
}

export class StudyRelatedSystemAssignment {
  
  public studyRelatedSystemAssignmentUid : string;
  
  public researchStudyUid : string;
  
  public systemEndpointUid : string;
  
  /**
   * semicolon separated list of custom role-names
   */
  public customRoles : string;
  
}

export class SystemConnection {
  
  public systemConnectionUid : string;
  
  public ownerInstituteUid : string;
  
  public hierSpäterJWTSEttings : string;
  
  public targetSystemEndpointUid : string;
  
  /**
   * *this field is optional
   */
  public dedicatedSiteRelatedSystemAssignmentUid : string;
  
}

export class SystemEndpoint {
  
  public systemEndpointUid : string;
  
  public providerInstituteUid : string;
  
  public availableRoles : string;
  
  public url : string;
  
  public approvedCert : string;
  
  public isPublic : string;
  
  public label : string;
  
}
