/* based on ORSCF StudyManagement Contract v1.6.1.0 */

import MedicalResearch.StudyManagement.Model;

namespace MedicalResearch.StudyManagement.StoreAccess {
  
  /**
   * Contains arguments for calling 'GetInstituteByInstituteUid'.
   * Method: Loads a specific Institute addressed by the given primary identifier. Returns null on failure, or if no record exists with the given identity.
   */
  public class GetInstituteByInstituteUidRequest {
    
    // Required Argument for 'GetInstituteByInstituteUid' (string): An <see href="https://de.wikipedia.org/wiki/Universally_Unique_Identifier">Universally Unique Identifier</see> which can be generated by any origin system and is used to address this ORSCF conform data record in decentralized environments. Note that this Identity must not be changed any more!
    [Required]
    public instituteUid : string { get; set; }
    
  }
  
  /**
   * Contains results from calling 'GetInstituteByInstituteUid'.
   * Method: Loads a specific Institute addressed by the given primary identifier. Returns null on failure, or if no record exists with the given identity.
   */
  public class GetInstituteByInstituteUidResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string { get; set; } = null;
    
    // Return-Value of 'GetInstituteByInstituteUid' (Institute)
    public @return : Institute { get; set; }
    
  }
  
  /**
   * Contains arguments for calling 'GetInstitutes'.
   * Method: Loads Institutes.
   */
  public class GetInstitutesRequest {
    
    // Optional Argument for 'GetInstitutes' (number?): Number of the page, which should be returned
    public page : number? { get; set; } = null;
    
    // Optional Argument for 'GetInstitutes' (number?): Max count of Institutes which should be returned
    public pageSize : number? { get; set; } = null;
    
  }
  
  /**
   * Contains results from calling 'GetInstitutes'.
   * Method: Loads Institutes.
   */
  public class GetInstitutesResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string { get; set; } = null;
    
    // Return-Value of 'GetInstitutes' (Institute[])
    public @return : Institute[] { get; set; }
    
  }
  
  /**
   * Contains arguments for calling 'SearchInstitutes'.
   * Method: Loads Institutes where values matching to the given filterExpression
   */
  public class SearchInstitutesRequest {
    
    // Required Argument for 'SearchInstitutes' (string): a filter expression like '((FieldName1 == "ABC" &amp;&amp; FieldName2 &gt; 12) || FieldName2 != "")'
    [Required]
    public filterExpression : string { get; set; }
    
    // Optional Argument for 'SearchInstitutes' (string): one or more property names which are used as sort order (before pagination)
    public sortingExpression : string { get; set; }
    
    // Optional Argument for 'SearchInstitutes' (number?): Number of the page, which should be returned
    public page : number? { get; set; } = null;
    
    // Optional Argument for 'SearchInstitutes' (number?): Max count of Institutes which should be returned
    public pageSize : number? { get; set; } = null;
    
  }
  
  /**
   * Contains results from calling 'SearchInstitutes'.
   * Method: Loads Institutes where values matching to the given filterExpression
   */
  public class SearchInstitutesResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string { get; set; } = null;
    
    // Return-Value of 'SearchInstitutes' (Institute[])
    public @return : Institute[] { get; set; }
    
  }
  
  /**
   * Contains arguments for calling 'AddNewInstitute'.
   * Method: Adds a new Institute and returns its primary identifier (or null on failure).
   */
  public class AddNewInstituteRequest {
    
    // Required Argument for 'AddNewInstitute' (Institute): Institute containing the new values
    [Required]
    public institute : Institute { get; set; }
    
  }
  
  /**
   * Contains results from calling 'AddNewInstitute'.
   * Method: Adds a new Institute and returns its primary identifier (or null on failure).
   */
  public class AddNewInstituteResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string { get; set; } = null;
    
    // Return-Value of 'AddNewInstitute' (Boolean)
    public @return : bool { get; set; }
    
  }
  
  /**
   * Contains arguments for calling 'UpdateInstitute'.
   * Method: Updates all values (which are not "FixedAfterCreation") of the given Institute addressed by the primary identifier fields within the given Institute. Returns false on failure or if no target record was found, otherwise true.
   */
  public class UpdateInstituteRequest {
    
    // Required Argument for 'UpdateInstitute' (Institute): Institute containing the new values (the primary identifier fields within the given Institute will be used to address the target record)
    [Required]
    public institute : Institute { get; set; }
    
  }
  
  /**
   * Contains results from calling 'UpdateInstitute'.
   * Method: Updates all values (which are not "FixedAfterCreation") of the given Institute addressed by the primary identifier fields within the given Institute. Returns false on failure or if no target record was found, otherwise true.
   */
  public class UpdateInstituteResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string { get; set; } = null;
    
    // Return-Value of 'UpdateInstitute' (Boolean)
    public @return : bool { get; set; }
    
  }
  
  /**
   * Contains arguments for calling 'UpdateInstituteByInstituteUid'.
   * Method: Updates all values (which are not "FixedAfterCreation") of the given Institute addressed by the supplementary given primary identifier. Returns false on failure or if no target record was found, otherwise true.
   */
  public class UpdateInstituteByInstituteUidRequest {
    
    // Required Argument for 'UpdateInstituteByInstituteUid' (string): An <see href="https://de.wikipedia.org/wiki/Universally_Unique_Identifier">Universally Unique Identifier</see> which can be generated by any origin system and is used to address this ORSCF conform data record in decentralized environments. Note that this Identity must not be changed any more!
    [Required]
    public instituteUid : string { get; set; }
    
    // Required Argument for 'UpdateInstituteByInstituteUid' (Institute): Institute containing the new values (the primary identifier fields within the given Institute will be ignored)
    [Required]
    public institute : Institute { get; set; }
    
  }
  
  /**
   * Contains results from calling 'UpdateInstituteByInstituteUid'.
   * Method: Updates all values (which are not "FixedAfterCreation") of the given Institute addressed by the supplementary given primary identifier. Returns false on failure or if no target record was found, otherwise true.
   */
  public class UpdateInstituteByInstituteUidResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string { get; set; } = null;
    
    // Return-Value of 'UpdateInstituteByInstituteUid' (Boolean)
    public @return : bool { get; set; }
    
  }
  
  /**
   * Contains arguments for calling 'DeleteInstituteByInstituteUid'.
   * Method: Deletes a specific Institute addressed by the given primary identifier. Returns false on failure or if no target record was found, otherwise true.
   */
  public class DeleteInstituteByInstituteUidRequest {
    
    // Required Argument for 'DeleteInstituteByInstituteUid' (string): An <see href="https://de.wikipedia.org/wiki/Universally_Unique_Identifier">Universally Unique Identifier</see> which can be generated by any origin system and is used to address this ORSCF conform data record in decentralized environments. Note that this Identity must not be changed any more!
    [Required]
    public instituteUid : string { get; set; }
    
  }
  
  /**
   * Contains results from calling 'DeleteInstituteByInstituteUid'.
   * Method: Deletes a specific Institute addressed by the given primary identifier. Returns false on failure or if no target record was found, otherwise true.
   */
  public class DeleteInstituteByInstituteUidResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string { get; set; } = null;
    
    // Return-Value of 'DeleteInstituteByInstituteUid' (Boolean)
    public @return : bool { get; set; }
    
  }
  
  /**
   * Contains arguments for calling 'GetResearchStudyByResearchStudyUid'.
   * Method: Loads a specific ResearchStudy addressed by the given primary identifier. Returns null on failure, or if no record exists with the given identity.
   */
  public class GetResearchStudyByResearchStudyUidRequest {
    
    // Required Argument for 'GetResearchStudyByResearchStudyUid' (string): An <see href="https://de.wikipedia.org/wiki/Universally_Unique_Identifier">Universally Unique Identifier</see> which can be generated by any origin system and is used to address this ORSCF conform data record in decentralized environments. Note that this Identity must not be changed any more!
    [Required]
    public researchStudyUid : string { get; set; }
    
  }
  
  /**
   * Contains results from calling 'GetResearchStudyByResearchStudyUid'.
   * Method: Loads a specific ResearchStudy addressed by the given primary identifier. Returns null on failure, or if no record exists with the given identity.
   */
  public class GetResearchStudyByResearchStudyUidResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string { get; set; } = null;
    
    // Return-Value of 'GetResearchStudyByResearchStudyUid' (ResearchStudy): entity, which relates to <see href="https://www.hl7.org/fhir/researchstudy.html">HL7.ResearchStudy</see>
    public @return : ResearchStudy { get; set; }
    
  }
  
  /**
   * Contains arguments for calling 'GetResearchStudies'.
   * Method: Loads ResearchStudies.
   */
  public class GetResearchStudiesRequest {
    
    // Optional Argument for 'GetResearchStudies' (number?): Number of the page, which should be returned
    public page : number? { get; set; } = null;
    
    // Optional Argument for 'GetResearchStudies' (number?): Max count of ResearchStudies which should be returned
    public pageSize : number? { get; set; } = null;
    
  }
  
  /**
   * Contains results from calling 'GetResearchStudies'.
   * Method: Loads ResearchStudies.
   */
  public class GetResearchStudiesResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string { get; set; } = null;
    
    // Return-Value of 'GetResearchStudies' (ResearchStudy[]): entity, which relates to <see href="https://www.hl7.org/fhir/researchstudy.html">HL7.ResearchStudy</see>
    public @return : ResearchStudy[] { get; set; }
    
  }
  
  /**
   * Contains arguments for calling 'SearchResearchStudies'.
   * Method: Loads ResearchStudies where values matching to the given filterExpression
   */
  public class SearchResearchStudiesRequest {
    
    // Required Argument for 'SearchResearchStudies' (string): a filter expression like '((FieldName1 == "ABC" &amp;&amp; FieldName2 &gt; 12) || FieldName2 != "")'
    [Required]
    public filterExpression : string { get; set; }
    
    // Optional Argument for 'SearchResearchStudies' (string): one or more property names which are used as sort order (before pagination)
    public sortingExpression : string { get; set; }
    
    // Optional Argument for 'SearchResearchStudies' (number?): Number of the page, which should be returned
    public page : number? { get; set; } = null;
    
    // Optional Argument for 'SearchResearchStudies' (number?): Max count of ResearchStudies which should be returned
    public pageSize : number? { get; set; } = null;
    
  }
  
  /**
   * Contains results from calling 'SearchResearchStudies'.
   * Method: Loads ResearchStudies where values matching to the given filterExpression
   */
  public class SearchResearchStudiesResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string { get; set; } = null;
    
    // Return-Value of 'SearchResearchStudies' (ResearchStudy[]): entity, which relates to <see href="https://www.hl7.org/fhir/researchstudy.html">HL7.ResearchStudy</see>
    public @return : ResearchStudy[] { get; set; }
    
  }
  
  /**
   * Contains arguments for calling 'AddNewResearchStudy'.
   * Method: Adds a new ResearchStudy and returns its primary identifier (or null on failure).
   */
  public class AddNewResearchStudyRequest {
    
    // Required Argument for 'AddNewResearchStudy' (ResearchStudy): ResearchStudy containing the new values
    [Required]
    public researchStudy : ResearchStudy { get; set; }
    
  }
  
  /**
   * Contains results from calling 'AddNewResearchStudy'.
   * Method: Adds a new ResearchStudy and returns its primary identifier (or null on failure).
   */
  public class AddNewResearchStudyResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string { get; set; } = null;
    
    // Return-Value of 'AddNewResearchStudy' (Boolean)
    public @return : bool { get; set; }
    
  }
  
  /**
   * Contains arguments for calling 'UpdateResearchStudy'.
   * Method: Updates all values (which are not "FixedAfterCreation") of the given ResearchStudy addressed by the primary identifier fields within the given ResearchStudy. Returns false on failure or if no target record was found, otherwise true.
   */
  public class UpdateResearchStudyRequest {
    
    // Required Argument for 'UpdateResearchStudy' (ResearchStudy): ResearchStudy containing the new values (the primary identifier fields within the given ResearchStudy will be used to address the target record)
    [Required]
    public researchStudy : ResearchStudy { get; set; }
    
  }
  
  /**
   * Contains results from calling 'UpdateResearchStudy'.
   * Method: Updates all values (which are not "FixedAfterCreation") of the given ResearchStudy addressed by the primary identifier fields within the given ResearchStudy. Returns false on failure or if no target record was found, otherwise true.
   */
  public class UpdateResearchStudyResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string { get; set; } = null;
    
    // Return-Value of 'UpdateResearchStudy' (Boolean)
    public @return : bool { get; set; }
    
  }
  
  /**
   * Contains arguments for calling 'UpdateResearchStudyByResearchStudyUid'.
   * Method: Updates all values (which are not "FixedAfterCreation") of the given ResearchStudy addressed by the supplementary given primary identifier. Returns false on failure or if no target record was found, otherwise true.
   */
  public class UpdateResearchStudyByResearchStudyUidRequest {
    
    // Required Argument for 'UpdateResearchStudyByResearchStudyUid' (string): An <see href="https://de.wikipedia.org/wiki/Universally_Unique_Identifier">Universally Unique Identifier</see> which can be generated by any origin system and is used to address this ORSCF conform data record in decentralized environments. Note that this Identity must not be changed any more!
    [Required]
    public researchStudyUid : string { get; set; }
    
    // Required Argument for 'UpdateResearchStudyByResearchStudyUid' (ResearchStudy): ResearchStudy containing the new values (the primary identifier fields within the given ResearchStudy will be ignored)
    [Required]
    public researchStudy : ResearchStudy { get; set; }
    
  }
  
  /**
   * Contains results from calling 'UpdateResearchStudyByResearchStudyUid'.
   * Method: Updates all values (which are not "FixedAfterCreation") of the given ResearchStudy addressed by the supplementary given primary identifier. Returns false on failure or if no target record was found, otherwise true.
   */
  public class UpdateResearchStudyByResearchStudyUidResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string { get; set; } = null;
    
    // Return-Value of 'UpdateResearchStudyByResearchStudyUid' (Boolean)
    public @return : bool { get; set; }
    
  }
  
  /**
   * Contains arguments for calling 'DeleteResearchStudyByResearchStudyUid'.
   * Method: Deletes a specific ResearchStudy addressed by the given primary identifier. Returns false on failure or if no target record was found, otherwise true.
   */
  public class DeleteResearchStudyByResearchStudyUidRequest {
    
    // Required Argument for 'DeleteResearchStudyByResearchStudyUid' (string): An <see href="https://de.wikipedia.org/wiki/Universally_Unique_Identifier">Universally Unique Identifier</see> which can be generated by any origin system and is used to address this ORSCF conform data record in decentralized environments. Note that this Identity must not be changed any more!
    [Required]
    public researchStudyUid : string { get; set; }
    
  }
  
  /**
   * Contains results from calling 'DeleteResearchStudyByResearchStudyUid'.
   * Method: Deletes a specific ResearchStudy addressed by the given primary identifier. Returns false on failure or if no target record was found, otherwise true.
   */
  public class DeleteResearchStudyByResearchStudyUidResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string { get; set; } = null;
    
    // Return-Value of 'DeleteResearchStudyByResearchStudyUid' (Boolean)
    public @return : bool { get; set; }
    
  }
  
  /**
   * Contains arguments for calling 'GetSiteBySiteUid'.
   * Method: Loads a specific Site addressed by the given primary identifier. Returns null on failure, or if no record exists with the given identity.
   */
  public class GetSiteBySiteUidRequest {
    
    // Required Argument for 'GetSiteBySiteUid' (string): An <see href="https://de.wikipedia.org/wiki/Universally_Unique_Identifier">Universally Unique Identifier</see> which can be generated by any origin system and is used to address this ORSCF conform data record in decentralized environments. Note that this Identity must not be changed any more!
    [Required]
    public siteUid : string { get; set; }
    
  }
  
  /**
   * Contains results from calling 'GetSiteBySiteUid'.
   * Method: Loads a specific Site addressed by the given primary identifier. Returns null on failure, or if no record exists with the given identity.
   */
  public class GetSiteBySiteUidResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string { get; set; } = null;
    
    // Return-Value of 'GetSiteBySiteUid' (Site)
    public @return : Site { get; set; }
    
  }
  
  /**
   * Contains arguments for calling 'GetSites'.
   * Method: Loads Sites.
   */
  public class GetSitesRequest {
    
    // Optional Argument for 'GetSites' (number?): Number of the page, which should be returned
    public page : number? { get; set; } = null;
    
    // Optional Argument for 'GetSites' (number?): Max count of Sites which should be returned
    public pageSize : number? { get; set; } = null;
    
  }
  
  /**
   * Contains results from calling 'GetSites'.
   * Method: Loads Sites.
   */
  public class GetSitesResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string { get; set; } = null;
    
    // Return-Value of 'GetSites' (Site[])
    public @return : Site[] { get; set; }
    
  }
  
  /**
   * Contains arguments for calling 'SearchSites'.
   * Method: Loads Sites where values matching to the given filterExpression
   */
  public class SearchSitesRequest {
    
    // Required Argument for 'SearchSites' (string): a filter expression like '((FieldName1 == "ABC" &amp;&amp; FieldName2 &gt; 12) || FieldName2 != "")'
    [Required]
    public filterExpression : string { get; set; }
    
    // Optional Argument for 'SearchSites' (string): one or more property names which are used as sort order (before pagination)
    public sortingExpression : string { get; set; }
    
    // Optional Argument for 'SearchSites' (number?): Number of the page, which should be returned
    public page : number? { get; set; } = null;
    
    // Optional Argument for 'SearchSites' (number?): Max count of Sites which should be returned
    public pageSize : number? { get; set; } = null;
    
  }
  
  /**
   * Contains results from calling 'SearchSites'.
   * Method: Loads Sites where values matching to the given filterExpression
   */
  public class SearchSitesResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string { get; set; } = null;
    
    // Return-Value of 'SearchSites' (Site[])
    public @return : Site[] { get; set; }
    
  }
  
  /**
   * Contains arguments for calling 'AddNewSite'.
   * Method: Adds a new Site and returns its primary identifier (or null on failure).
   */
  public class AddNewSiteRequest {
    
    // Required Argument for 'AddNewSite' (Site): Site containing the new values
    [Required]
    public site : Site { get; set; }
    
  }
  
  /**
   * Contains results from calling 'AddNewSite'.
   * Method: Adds a new Site and returns its primary identifier (or null on failure).
   */
  public class AddNewSiteResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string { get; set; } = null;
    
    // Return-Value of 'AddNewSite' (Boolean)
    public @return : bool { get; set; }
    
  }
  
  /**
   * Contains arguments for calling 'UpdateSite'.
   * Method: Updates all values (which are not "FixedAfterCreation") of the given Site addressed by the primary identifier fields within the given Site. Returns false on failure or if no target record was found, otherwise true.
   */
  public class UpdateSiteRequest {
    
    // Required Argument for 'UpdateSite' (Site): Site containing the new values (the primary identifier fields within the given Site will be used to address the target record)
    [Required]
    public site : Site { get; set; }
    
  }
  
  /**
   * Contains results from calling 'UpdateSite'.
   * Method: Updates all values (which are not "FixedAfterCreation") of the given Site addressed by the primary identifier fields within the given Site. Returns false on failure or if no target record was found, otherwise true.
   */
  public class UpdateSiteResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string { get; set; } = null;
    
    // Return-Value of 'UpdateSite' (Boolean)
    public @return : bool { get; set; }
    
  }
  
  /**
   * Contains arguments for calling 'UpdateSiteBySiteUid'.
   * Method: Updates all values (which are not "FixedAfterCreation") of the given Site addressed by the supplementary given primary identifier. Returns false on failure or if no target record was found, otherwise true.
   */
  public class UpdateSiteBySiteUidRequest {
    
    // Required Argument for 'UpdateSiteBySiteUid' (string): An <see href="https://de.wikipedia.org/wiki/Universally_Unique_Identifier">Universally Unique Identifier</see> which can be generated by any origin system and is used to address this ORSCF conform data record in decentralized environments. Note that this Identity must not be changed any more!
    [Required]
    public siteUid : string { get; set; }
    
    // Required Argument for 'UpdateSiteBySiteUid' (Site): Site containing the new values (the primary identifier fields within the given Site will be ignored)
    [Required]
    public site : Site { get; set; }
    
  }
  
  /**
   * Contains results from calling 'UpdateSiteBySiteUid'.
   * Method: Updates all values (which are not "FixedAfterCreation") of the given Site addressed by the supplementary given primary identifier. Returns false on failure or if no target record was found, otherwise true.
   */
  public class UpdateSiteBySiteUidResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string { get; set; } = null;
    
    // Return-Value of 'UpdateSiteBySiteUid' (Boolean)
    public @return : bool { get; set; }
    
  }
  
  /**
   * Contains arguments for calling 'DeleteSiteBySiteUid'.
   * Method: Deletes a specific Site addressed by the given primary identifier. Returns false on failure or if no target record was found, otherwise true.
   */
  public class DeleteSiteBySiteUidRequest {
    
    // Required Argument for 'DeleteSiteBySiteUid' (string): An <see href="https://de.wikipedia.org/wiki/Universally_Unique_Identifier">Universally Unique Identifier</see> which can be generated by any origin system and is used to address this ORSCF conform data record in decentralized environments. Note that this Identity must not be changed any more!
    [Required]
    public siteUid : string { get; set; }
    
  }
  
  /**
   * Contains results from calling 'DeleteSiteBySiteUid'.
   * Method: Deletes a specific Site addressed by the given primary identifier. Returns false on failure or if no target record was found, otherwise true.
   */
  public class DeleteSiteBySiteUidResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string { get; set; } = null;
    
    // Return-Value of 'DeleteSiteBySiteUid' (Boolean)
    public @return : bool { get; set; }
    
  }
  
  /**
   * Contains arguments for calling 'GetSystemEndpointBySystemEndpointUid'.
   * Method: Loads a specific SystemEndpoint addressed by the given primary identifier. Returns null on failure, or if no record exists with the given identity.
   */
  public class GetSystemEndpointBySystemEndpointUidRequest {
    
    // Required Argument for 'GetSystemEndpointBySystemEndpointUid' (string): Represents the primary identity of a SystemEndpoint
    [Required]
    public systemEndpointUid : string { get; set; }
    
  }
  
  /**
   * Contains results from calling 'GetSystemEndpointBySystemEndpointUid'.
   * Method: Loads a specific SystemEndpoint addressed by the given primary identifier. Returns null on failure, or if no record exists with the given identity.
   */
  public class GetSystemEndpointBySystemEndpointUidResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string { get; set; } = null;
    
    // Return-Value of 'GetSystemEndpointBySystemEndpointUid' (SystemEndpoint)
    public @return : SystemEndpoint { get; set; }
    
  }
  
  /**
   * Contains arguments for calling 'GetSystemEndpoints'.
   * Method: Loads SystemEndpoints.
   */
  public class GetSystemEndpointsRequest {
    
    // Optional Argument for 'GetSystemEndpoints' (number?): Number of the page, which should be returned
    public page : number? { get; set; } = null;
    
    // Optional Argument for 'GetSystemEndpoints' (number?): Max count of SystemEndpoints which should be returned
    public pageSize : number? { get; set; } = null;
    
  }
  
  /**
   * Contains results from calling 'GetSystemEndpoints'.
   * Method: Loads SystemEndpoints.
   */
  public class GetSystemEndpointsResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string { get; set; } = null;
    
    // Return-Value of 'GetSystemEndpoints' (SystemEndpoint[])
    public @return : SystemEndpoint[] { get; set; }
    
  }
  
  /**
   * Contains arguments for calling 'SearchSystemEndpoints'.
   * Method: Loads SystemEndpoints where values matching to the given filterExpression
   */
  public class SearchSystemEndpointsRequest {
    
    // Required Argument for 'SearchSystemEndpoints' (string): a filter expression like '((FieldName1 == "ABC" &amp;&amp; FieldName2 &gt; 12) || FieldName2 != "")'
    [Required]
    public filterExpression : string { get; set; }
    
    // Optional Argument for 'SearchSystemEndpoints' (string): one or more property names which are used as sort order (before pagination)
    public sortingExpression : string { get; set; }
    
    // Optional Argument for 'SearchSystemEndpoints' (number?): Number of the page, which should be returned
    public page : number? { get; set; } = null;
    
    // Optional Argument for 'SearchSystemEndpoints' (number?): Max count of SystemEndpoints which should be returned
    public pageSize : number? { get; set; } = null;
    
  }
  
  /**
   * Contains results from calling 'SearchSystemEndpoints'.
   * Method: Loads SystemEndpoints where values matching to the given filterExpression
   */
  public class SearchSystemEndpointsResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string { get; set; } = null;
    
    // Return-Value of 'SearchSystemEndpoints' (SystemEndpoint[])
    public @return : SystemEndpoint[] { get; set; }
    
  }
  
  /**
   * Contains arguments for calling 'AddNewSystemEndpoint'.
   * Method: Adds a new SystemEndpoint and returns its primary identifier (or null on failure).
   */
  public class AddNewSystemEndpointRequest {
    
    // Required Argument for 'AddNewSystemEndpoint' (SystemEndpoint): SystemEndpoint containing the new values
    [Required]
    public systemEndpoint : SystemEndpoint { get; set; }
    
  }
  
  /**
   * Contains results from calling 'AddNewSystemEndpoint'.
   * Method: Adds a new SystemEndpoint and returns its primary identifier (or null on failure).
   */
  public class AddNewSystemEndpointResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string { get; set; } = null;
    
    // Return-Value of 'AddNewSystemEndpoint' (Boolean)
    public @return : bool { get; set; }
    
  }
  
  /**
   * Contains arguments for calling 'UpdateSystemEndpoint'.
   * Method: Updates all values (which are not "FixedAfterCreation") of the given SystemEndpoint addressed by the primary identifier fields within the given SystemEndpoint. Returns false on failure or if no target record was found, otherwise true.
   */
  public class UpdateSystemEndpointRequest {
    
    // Required Argument for 'UpdateSystemEndpoint' (SystemEndpoint): SystemEndpoint containing the new values (the primary identifier fields within the given SystemEndpoint will be used to address the target record)
    [Required]
    public systemEndpoint : SystemEndpoint { get; set; }
    
  }
  
  /**
   * Contains results from calling 'UpdateSystemEndpoint'.
   * Method: Updates all values (which are not "FixedAfterCreation") of the given SystemEndpoint addressed by the primary identifier fields within the given SystemEndpoint. Returns false on failure or if no target record was found, otherwise true.
   */
  public class UpdateSystemEndpointResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string { get; set; } = null;
    
    // Return-Value of 'UpdateSystemEndpoint' (Boolean)
    public @return : bool { get; set; }
    
  }
  
  /**
   * Contains arguments for calling 'UpdateSystemEndpointBySystemEndpointUid'.
   * Method: Updates all values (which are not "FixedAfterCreation") of the given SystemEndpoint addressed by the supplementary given primary identifier. Returns false on failure or if no target record was found, otherwise true.
   */
  public class UpdateSystemEndpointBySystemEndpointUidRequest {
    
    // Required Argument for 'UpdateSystemEndpointBySystemEndpointUid' (string): Represents the primary identity of a SystemEndpoint
    [Required]
    public systemEndpointUid : string { get; set; }
    
    // Required Argument for 'UpdateSystemEndpointBySystemEndpointUid' (SystemEndpoint): SystemEndpoint containing the new values (the primary identifier fields within the given SystemEndpoint will be ignored)
    [Required]
    public systemEndpoint : SystemEndpoint { get; set; }
    
  }
  
  /**
   * Contains results from calling 'UpdateSystemEndpointBySystemEndpointUid'.
   * Method: Updates all values (which are not "FixedAfterCreation") of the given SystemEndpoint addressed by the supplementary given primary identifier. Returns false on failure or if no target record was found, otherwise true.
   */
  public class UpdateSystemEndpointBySystemEndpointUidResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string { get; set; } = null;
    
    // Return-Value of 'UpdateSystemEndpointBySystemEndpointUid' (Boolean)
    public @return : bool { get; set; }
    
  }
  
  /**
   * Contains arguments for calling 'DeleteSystemEndpointBySystemEndpointUid'.
   * Method: Deletes a specific SystemEndpoint addressed by the given primary identifier. Returns false on failure or if no target record was found, otherwise true.
   */
  public class DeleteSystemEndpointBySystemEndpointUidRequest {
    
    // Required Argument for 'DeleteSystemEndpointBySystemEndpointUid' (string): Represents the primary identity of a SystemEndpoint
    [Required]
    public systemEndpointUid : string { get; set; }
    
  }
  
  /**
   * Contains results from calling 'DeleteSystemEndpointBySystemEndpointUid'.
   * Method: Deletes a specific SystemEndpoint addressed by the given primary identifier. Returns false on failure or if no target record was found, otherwise true.
   */
  public class DeleteSystemEndpointBySystemEndpointUidResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string { get; set; } = null;
    
    // Return-Value of 'DeleteSystemEndpointBySystemEndpointUid' (Boolean)
    public @return : bool { get; set; }
    
  }
  
  /**
   * Contains arguments for calling 'GetInstituteRelatedSystemAssignmentByInstituteRelatedSystemAssignemntUid'.
   * Method: Loads a specific InstituteRelatedSystemAssignment addressed by the given primary identifier. Returns null on failure, or if no record exists with the given identity.
   */
  public class GetInstituteRelatedSystemAssignmentByInstituteRelatedSystemAssignemntUidRequest {
    
    // Required Argument for 'GetInstituteRelatedSystemAssignmentByInstituteRelatedSystemAssignemntUid' (string): Represents the primary identity of a InstituteRelatedSystemAssignment
    [Required]
    public instituteRelatedSystemAssignemntUid : string { get; set; }
    
  }
  
  /**
   * Contains results from calling 'GetInstituteRelatedSystemAssignmentByInstituteRelatedSystemAssignemntUid'.
   * Method: Loads a specific InstituteRelatedSystemAssignment addressed by the given primary identifier. Returns null on failure, or if no record exists with the given identity.
   */
  public class GetInstituteRelatedSystemAssignmentByInstituteRelatedSystemAssignemntUidResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string { get; set; } = null;
    
    // Return-Value of 'GetInstituteRelatedSystemAssignmentByInstituteRelatedSystemAssignemntUid' (InstituteRelatedSystemAssignment)
    public @return : InstituteRelatedSystemAssignment { get; set; }
    
  }
  
  /**
   * Contains arguments for calling 'GetInstituteRelatedSystemAssignments'.
   * Method: Loads InstituteRelatedSystemAssignments.
   */
  public class GetInstituteRelatedSystemAssignmentsRequest {
    
    // Optional Argument for 'GetInstituteRelatedSystemAssignments' (number?): Number of the page, which should be returned
    public page : number? { get; set; } = null;
    
    // Optional Argument for 'GetInstituteRelatedSystemAssignments' (number?): Max count of InstituteRelatedSystemAssignments which should be returned
    public pageSize : number? { get; set; } = null;
    
  }
  
  /**
   * Contains results from calling 'GetInstituteRelatedSystemAssignments'.
   * Method: Loads InstituteRelatedSystemAssignments.
   */
  public class GetInstituteRelatedSystemAssignmentsResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string { get; set; } = null;
    
    // Return-Value of 'GetInstituteRelatedSystemAssignments' (InstituteRelatedSystemAssignment[])
    public @return : InstituteRelatedSystemAssignment[] { get; set; }
    
  }
  
  /**
   * Contains arguments for calling 'SearchInstituteRelatedSystemAssignments'.
   * Method: Loads InstituteRelatedSystemAssignments where values matching to the given filterExpression
   */
  public class SearchInstituteRelatedSystemAssignmentsRequest {
    
    // Required Argument for 'SearchInstituteRelatedSystemAssignments' (string): a filter expression like '((FieldName1 == "ABC" &amp;&amp; FieldName2 &gt; 12) || FieldName2 != "")'
    [Required]
    public filterExpression : string { get; set; }
    
    // Optional Argument for 'SearchInstituteRelatedSystemAssignments' (string): one or more property names which are used as sort order (before pagination)
    public sortingExpression : string { get; set; }
    
    // Optional Argument for 'SearchInstituteRelatedSystemAssignments' (number?): Number of the page, which should be returned
    public page : number? { get; set; } = null;
    
    // Optional Argument for 'SearchInstituteRelatedSystemAssignments' (number?): Max count of InstituteRelatedSystemAssignments which should be returned
    public pageSize : number? { get; set; } = null;
    
  }
  
  /**
   * Contains results from calling 'SearchInstituteRelatedSystemAssignments'.
   * Method: Loads InstituteRelatedSystemAssignments where values matching to the given filterExpression
   */
  public class SearchInstituteRelatedSystemAssignmentsResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string { get; set; } = null;
    
    // Return-Value of 'SearchInstituteRelatedSystemAssignments' (InstituteRelatedSystemAssignment[])
    public @return : InstituteRelatedSystemAssignment[] { get; set; }
    
  }
  
  /**
   * Contains arguments for calling 'AddNewInstituteRelatedSystemAssignment'.
   * Method: Adds a new InstituteRelatedSystemAssignment and returns its primary identifier (or null on failure).
   */
  public class AddNewInstituteRelatedSystemAssignmentRequest {
    
    // Required Argument for 'AddNewInstituteRelatedSystemAssignment' (InstituteRelatedSystemAssignment): InstituteRelatedSystemAssignment containing the new values
    [Required]
    public instituteRelatedSystemAssignment : InstituteRelatedSystemAssignment { get; set; }
    
  }
  
  /**
   * Contains results from calling 'AddNewInstituteRelatedSystemAssignment'.
   * Method: Adds a new InstituteRelatedSystemAssignment and returns its primary identifier (or null on failure).
   */
  public class AddNewInstituteRelatedSystemAssignmentResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string { get; set; } = null;
    
    // Return-Value of 'AddNewInstituteRelatedSystemAssignment' (Boolean)
    public @return : bool { get; set; }
    
  }
  
  /**
   * Contains arguments for calling 'UpdateInstituteRelatedSystemAssignment'.
   * Method: Updates all values (which are not "FixedAfterCreation") of the given InstituteRelatedSystemAssignment addressed by the primary identifier fields within the given InstituteRelatedSystemAssignment. Returns false on failure or if no target record was found, otherwise true.
   */
  public class UpdateInstituteRelatedSystemAssignmentRequest {
    
    // Required Argument for 'UpdateInstituteRelatedSystemAssignment' (InstituteRelatedSystemAssignment): InstituteRelatedSystemAssignment containing the new values (the primary identifier fields within the given InstituteRelatedSystemAssignment will be used to address the target record)
    [Required]
    public instituteRelatedSystemAssignment : InstituteRelatedSystemAssignment { get; set; }
    
  }
  
  /**
   * Contains results from calling 'UpdateInstituteRelatedSystemAssignment'.
   * Method: Updates all values (which are not "FixedAfterCreation") of the given InstituteRelatedSystemAssignment addressed by the primary identifier fields within the given InstituteRelatedSystemAssignment. Returns false on failure or if no target record was found, otherwise true.
   */
  public class UpdateInstituteRelatedSystemAssignmentResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string { get; set; } = null;
    
    // Return-Value of 'UpdateInstituteRelatedSystemAssignment' (Boolean)
    public @return : bool { get; set; }
    
  }
  
  /**
   * Contains arguments for calling 'UpdateInstituteRelatedSystemAssignmentByInstituteRelatedSystemAssignemntUid'.
   * Method: Updates all values (which are not "FixedAfterCreation") of the given InstituteRelatedSystemAssignment addressed by the supplementary given primary identifier. Returns false on failure or if no target record was found, otherwise true.
   */
  public class UpdateInstituteRelatedSystemAssignmentByInstituteRelatedSystemAssignemntUidRequest {
    
    // Required Argument for 'UpdateInstituteRelatedSystemAssignmentByInstituteRelatedSystemAssignemntUid' (string): Represents the primary identity of a InstituteRelatedSystemAssignment
    [Required]
    public instituteRelatedSystemAssignemntUid : string { get; set; }
    
    // Required Argument for 'UpdateInstituteRelatedSystemAssignmentByInstituteRelatedSystemAssignemntUid' (InstituteRelatedSystemAssignment): InstituteRelatedSystemAssignment containing the new values (the primary identifier fields within the given InstituteRelatedSystemAssignment will be ignored)
    [Required]
    public instituteRelatedSystemAssignment : InstituteRelatedSystemAssignment { get; set; }
    
  }
  
  /**
   * Contains results from calling 'UpdateInstituteRelatedSystemAssignmentByInstituteRelatedSystemAssignemntUid'.
   * Method: Updates all values (which are not "FixedAfterCreation") of the given InstituteRelatedSystemAssignment addressed by the supplementary given primary identifier. Returns false on failure or if no target record was found, otherwise true.
   */
  public class UpdateInstituteRelatedSystemAssignmentByInstituteRelatedSystemAssignemntUidResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string { get; set; } = null;
    
    // Return-Value of 'UpdateInstituteRelatedSystemAssignmentByInstituteRelatedSystemAssignemntUid' (Boolean)
    public @return : bool { get; set; }
    
  }
  
  /**
   * Contains arguments for calling 'DeleteInstituteRelatedSystemAssignmentByInstituteRelatedSystemAssignemntUid'.
   * Method: Deletes a specific InstituteRelatedSystemAssignment addressed by the given primary identifier. Returns false on failure or if no target record was found, otherwise true.
   */
  public class DeleteInstituteRelatedSystemAssignmentByInstituteRelatedSystemAssignemntUidRequest {
    
    // Required Argument for 'DeleteInstituteRelatedSystemAssignmentByInstituteRelatedSystemAssignemntUid' (string): Represents the primary identity of a InstituteRelatedSystemAssignment
    [Required]
    public instituteRelatedSystemAssignemntUid : string { get; set; }
    
  }
  
  /**
   * Contains results from calling 'DeleteInstituteRelatedSystemAssignmentByInstituteRelatedSystemAssignemntUid'.
   * Method: Deletes a specific InstituteRelatedSystemAssignment addressed by the given primary identifier. Returns false on failure or if no target record was found, otherwise true.
   */
  public class DeleteInstituteRelatedSystemAssignmentByInstituteRelatedSystemAssignemntUidResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string { get; set; } = null;
    
    // Return-Value of 'DeleteInstituteRelatedSystemAssignmentByInstituteRelatedSystemAssignemntUid' (Boolean)
    public @return : bool { get; set; }
    
  }
  
  /**
   * Contains arguments for calling 'GetSystemConnectionBySystemConnectionUid'.
   * Method: Loads a specific SystemConnection addressed by the given primary identifier. Returns null on failure, or if no record exists with the given identity.
   */
  public class GetSystemConnectionBySystemConnectionUidRequest {
    
    // Required Argument for 'GetSystemConnectionBySystemConnectionUid' (string): Represents the primary identity of a SystemConnection
    [Required]
    public systemConnectionUid : string { get; set; }
    
  }
  
  /**
   * Contains results from calling 'GetSystemConnectionBySystemConnectionUid'.
   * Method: Loads a specific SystemConnection addressed by the given primary identifier. Returns null on failure, or if no record exists with the given identity.
   */
  public class GetSystemConnectionBySystemConnectionUidResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string { get; set; } = null;
    
    // Return-Value of 'GetSystemConnectionBySystemConnectionUid' (SystemConnection)
    public @return : SystemConnection { get; set; }
    
  }
  
  /**
   * Contains arguments for calling 'GetSystemConnections'.
   * Method: Loads SystemConnections.
   */
  public class GetSystemConnectionsRequest {
    
    // Optional Argument for 'GetSystemConnections' (number?): Number of the page, which should be returned
    public page : number? { get; set; } = null;
    
    // Optional Argument for 'GetSystemConnections' (number?): Max count of SystemConnections which should be returned
    public pageSize : number? { get; set; } = null;
    
  }
  
  /**
   * Contains results from calling 'GetSystemConnections'.
   * Method: Loads SystemConnections.
   */
  public class GetSystemConnectionsResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string { get; set; } = null;
    
    // Return-Value of 'GetSystemConnections' (SystemConnection[])
    public @return : SystemConnection[] { get; set; }
    
  }
  
  /**
   * Contains arguments for calling 'SearchSystemConnections'.
   * Method: Loads SystemConnections where values matching to the given filterExpression
   */
  public class SearchSystemConnectionsRequest {
    
    // Required Argument for 'SearchSystemConnections' (string): a filter expression like '((FieldName1 == "ABC" &amp;&amp; FieldName2 &gt; 12) || FieldName2 != "")'
    [Required]
    public filterExpression : string { get; set; }
    
    // Optional Argument for 'SearchSystemConnections' (string): one or more property names which are used as sort order (before pagination)
    public sortingExpression : string { get; set; }
    
    // Optional Argument for 'SearchSystemConnections' (number?): Number of the page, which should be returned
    public page : number? { get; set; } = null;
    
    // Optional Argument for 'SearchSystemConnections' (number?): Max count of SystemConnections which should be returned
    public pageSize : number? { get; set; } = null;
    
  }
  
  /**
   * Contains results from calling 'SearchSystemConnections'.
   * Method: Loads SystemConnections where values matching to the given filterExpression
   */
  public class SearchSystemConnectionsResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string { get; set; } = null;
    
    // Return-Value of 'SearchSystemConnections' (SystemConnection[])
    public @return : SystemConnection[] { get; set; }
    
  }
  
  /**
   * Contains arguments for calling 'AddNewSystemConnection'.
   * Method: Adds a new SystemConnection and returns its primary identifier (or null on failure).
   */
  public class AddNewSystemConnectionRequest {
    
    // Required Argument for 'AddNewSystemConnection' (SystemConnection): SystemConnection containing the new values
    [Required]
    public systemConnection : SystemConnection { get; set; }
    
  }
  
  /**
   * Contains results from calling 'AddNewSystemConnection'.
   * Method: Adds a new SystemConnection and returns its primary identifier (or null on failure).
   */
  public class AddNewSystemConnectionResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string { get; set; } = null;
    
    // Return-Value of 'AddNewSystemConnection' (Boolean)
    public @return : bool { get; set; }
    
  }
  
  /**
   * Contains arguments for calling 'UpdateSystemConnection'.
   * Method: Updates all values (which are not "FixedAfterCreation") of the given SystemConnection addressed by the primary identifier fields within the given SystemConnection. Returns false on failure or if no target record was found, otherwise true.
   */
  public class UpdateSystemConnectionRequest {
    
    // Required Argument for 'UpdateSystemConnection' (SystemConnection): SystemConnection containing the new values (the primary identifier fields within the given SystemConnection will be used to address the target record)
    [Required]
    public systemConnection : SystemConnection { get; set; }
    
  }
  
  /**
   * Contains results from calling 'UpdateSystemConnection'.
   * Method: Updates all values (which are not "FixedAfterCreation") of the given SystemConnection addressed by the primary identifier fields within the given SystemConnection. Returns false on failure or if no target record was found, otherwise true.
   */
  public class UpdateSystemConnectionResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string { get; set; } = null;
    
    // Return-Value of 'UpdateSystemConnection' (Boolean)
    public @return : bool { get; set; }
    
  }
  
  /**
   * Contains arguments for calling 'UpdateSystemConnectionBySystemConnectionUid'.
   * Method: Updates all values (which are not "FixedAfterCreation") of the given SystemConnection addressed by the supplementary given primary identifier. Returns false on failure or if no target record was found, otherwise true.
   */
  public class UpdateSystemConnectionBySystemConnectionUidRequest {
    
    // Required Argument for 'UpdateSystemConnectionBySystemConnectionUid' (string): Represents the primary identity of a SystemConnection
    [Required]
    public systemConnectionUid : string { get; set; }
    
    // Required Argument for 'UpdateSystemConnectionBySystemConnectionUid' (SystemConnection): SystemConnection containing the new values (the primary identifier fields within the given SystemConnection will be ignored)
    [Required]
    public systemConnection : SystemConnection { get; set; }
    
  }
  
  /**
   * Contains results from calling 'UpdateSystemConnectionBySystemConnectionUid'.
   * Method: Updates all values (which are not "FixedAfterCreation") of the given SystemConnection addressed by the supplementary given primary identifier. Returns false on failure or if no target record was found, otherwise true.
   */
  public class UpdateSystemConnectionBySystemConnectionUidResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string { get; set; } = null;
    
    // Return-Value of 'UpdateSystemConnectionBySystemConnectionUid' (Boolean)
    public @return : bool { get; set; }
    
  }
  
  /**
   * Contains arguments for calling 'DeleteSystemConnectionBySystemConnectionUid'.
   * Method: Deletes a specific SystemConnection addressed by the given primary identifier. Returns false on failure or if no target record was found, otherwise true.
   */
  public class DeleteSystemConnectionBySystemConnectionUidRequest {
    
    // Required Argument for 'DeleteSystemConnectionBySystemConnectionUid' (string): Represents the primary identity of a SystemConnection
    [Required]
    public systemConnectionUid : string { get; set; }
    
  }
  
  /**
   * Contains results from calling 'DeleteSystemConnectionBySystemConnectionUid'.
   * Method: Deletes a specific SystemConnection addressed by the given primary identifier. Returns false on failure or if no target record was found, otherwise true.
   */
  public class DeleteSystemConnectionBySystemConnectionUidResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string { get; set; } = null;
    
    // Return-Value of 'DeleteSystemConnectionBySystemConnectionUid' (Boolean)
    public @return : bool { get; set; }
    
  }
  
  /**
   * Contains arguments for calling 'GetInvolvedPersonByInvolvedPersonUid'.
   * Method: Loads a specific InvolvedPerson addressed by the given primary identifier. Returns null on failure, or if no record exists with the given identity.
   */
  public class GetInvolvedPersonByInvolvedPersonUidRequest {
    
    // Required Argument for 'GetInvolvedPersonByInvolvedPersonUid' (string): An <see href="https://de.wikipedia.org/wiki/Universally_Unique_Identifier">Universally Unique Identifier</see> which can be generated by any origin system and is used to address this ORSCF conform data record in decentralized environments. Note that this Identity must not be changed any more!
    [Required]
    public involvedPersonUid : string { get; set; }
    
  }
  
  /**
   * Contains results from calling 'GetInvolvedPersonByInvolvedPersonUid'.
   * Method: Loads a specific InvolvedPerson addressed by the given primary identifier. Returns null on failure, or if no record exists with the given identity.
   */
  public class GetInvolvedPersonByInvolvedPersonUidResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string { get; set; } = null;
    
    // Return-Value of 'GetInvolvedPersonByInvolvedPersonUid' (InvolvedPerson)
    public @return : InvolvedPerson { get; set; }
    
  }
  
  /**
   * Contains arguments for calling 'GetInvolvedPersons'.
   * Method: Loads InvolvedPersons.
   */
  public class GetInvolvedPersonsRequest {
    
    // Optional Argument for 'GetInvolvedPersons' (number?): Number of the page, which should be returned
    public page : number? { get; set; } = null;
    
    // Optional Argument for 'GetInvolvedPersons' (number?): Max count of InvolvedPersons which should be returned
    public pageSize : number? { get; set; } = null;
    
  }
  
  /**
   * Contains results from calling 'GetInvolvedPersons'.
   * Method: Loads InvolvedPersons.
   */
  public class GetInvolvedPersonsResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string { get; set; } = null;
    
    // Return-Value of 'GetInvolvedPersons' (InvolvedPerson[])
    public @return : InvolvedPerson[] { get; set; }
    
  }
  
  /**
   * Contains arguments for calling 'SearchInvolvedPersons'.
   * Method: Loads InvolvedPersons where values matching to the given filterExpression
   */
  public class SearchInvolvedPersonsRequest {
    
    // Required Argument for 'SearchInvolvedPersons' (string): a filter expression like '((FieldName1 == "ABC" &amp;&amp; FieldName2 &gt; 12) || FieldName2 != "")'
    [Required]
    public filterExpression : string { get; set; }
    
    // Optional Argument for 'SearchInvolvedPersons' (string): one or more property names which are used as sort order (before pagination)
    public sortingExpression : string { get; set; }
    
    // Optional Argument for 'SearchInvolvedPersons' (number?): Number of the page, which should be returned
    public page : number? { get; set; } = null;
    
    // Optional Argument for 'SearchInvolvedPersons' (number?): Max count of InvolvedPersons which should be returned
    public pageSize : number? { get; set; } = null;
    
  }
  
  /**
   * Contains results from calling 'SearchInvolvedPersons'.
   * Method: Loads InvolvedPersons where values matching to the given filterExpression
   */
  public class SearchInvolvedPersonsResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string { get; set; } = null;
    
    // Return-Value of 'SearchInvolvedPersons' (InvolvedPerson[])
    public @return : InvolvedPerson[] { get; set; }
    
  }
  
  /**
   * Contains arguments for calling 'AddNewInvolvedPerson'.
   * Method: Adds a new InvolvedPerson and returns its primary identifier (or null on failure).
   */
  public class AddNewInvolvedPersonRequest {
    
    // Required Argument for 'AddNewInvolvedPerson' (InvolvedPerson): InvolvedPerson containing the new values
    [Required]
    public involvedPerson : InvolvedPerson { get; set; }
    
  }
  
  /**
   * Contains results from calling 'AddNewInvolvedPerson'.
   * Method: Adds a new InvolvedPerson and returns its primary identifier (or null on failure).
   */
  public class AddNewInvolvedPersonResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string { get; set; } = null;
    
    // Return-Value of 'AddNewInvolvedPerson' (Boolean)
    public @return : bool { get; set; }
    
  }
  
  /**
   * Contains arguments for calling 'UpdateInvolvedPerson'.
   * Method: Updates all values (which are not "FixedAfterCreation") of the given InvolvedPerson addressed by the primary identifier fields within the given InvolvedPerson. Returns false on failure or if no target record was found, otherwise true.
   */
  public class UpdateInvolvedPersonRequest {
    
    // Required Argument for 'UpdateInvolvedPerson' (InvolvedPerson): InvolvedPerson containing the new values (the primary identifier fields within the given InvolvedPerson will be used to address the target record)
    [Required]
    public involvedPerson : InvolvedPerson { get; set; }
    
  }
  
  /**
   * Contains results from calling 'UpdateInvolvedPerson'.
   * Method: Updates all values (which are not "FixedAfterCreation") of the given InvolvedPerson addressed by the primary identifier fields within the given InvolvedPerson. Returns false on failure or if no target record was found, otherwise true.
   */
  public class UpdateInvolvedPersonResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string { get; set; } = null;
    
    // Return-Value of 'UpdateInvolvedPerson' (Boolean)
    public @return : bool { get; set; }
    
  }
  
  /**
   * Contains arguments for calling 'UpdateInvolvedPersonByInvolvedPersonUid'.
   * Method: Updates all values (which are not "FixedAfterCreation") of the given InvolvedPerson addressed by the supplementary given primary identifier. Returns false on failure or if no target record was found, otherwise true.
   */
  public class UpdateInvolvedPersonByInvolvedPersonUidRequest {
    
    // Required Argument for 'UpdateInvolvedPersonByInvolvedPersonUid' (string): An <see href="https://de.wikipedia.org/wiki/Universally_Unique_Identifier">Universally Unique Identifier</see> which can be generated by any origin system and is used to address this ORSCF conform data record in decentralized environments. Note that this Identity must not be changed any more!
    [Required]
    public involvedPersonUid : string { get; set; }
    
    // Required Argument for 'UpdateInvolvedPersonByInvolvedPersonUid' (InvolvedPerson): InvolvedPerson containing the new values (the primary identifier fields within the given InvolvedPerson will be ignored)
    [Required]
    public involvedPerson : InvolvedPerson { get; set; }
    
  }
  
  /**
   * Contains results from calling 'UpdateInvolvedPersonByInvolvedPersonUid'.
   * Method: Updates all values (which are not "FixedAfterCreation") of the given InvolvedPerson addressed by the supplementary given primary identifier. Returns false on failure or if no target record was found, otherwise true.
   */
  public class UpdateInvolvedPersonByInvolvedPersonUidResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string { get; set; } = null;
    
    // Return-Value of 'UpdateInvolvedPersonByInvolvedPersonUid' (Boolean)
    public @return : bool { get; set; }
    
  }
  
  /**
   * Contains arguments for calling 'DeleteInvolvedPersonByInvolvedPersonUid'.
   * Method: Deletes a specific InvolvedPerson addressed by the given primary identifier. Returns false on failure or if no target record was found, otherwise true.
   */
  public class DeleteInvolvedPersonByInvolvedPersonUidRequest {
    
    // Required Argument for 'DeleteInvolvedPersonByInvolvedPersonUid' (string): An <see href="https://de.wikipedia.org/wiki/Universally_Unique_Identifier">Universally Unique Identifier</see> which can be generated by any origin system and is used to address this ORSCF conform data record in decentralized environments. Note that this Identity must not be changed any more!
    [Required]
    public involvedPersonUid : string { get; set; }
    
  }
  
  /**
   * Contains results from calling 'DeleteInvolvedPersonByInvolvedPersonUid'.
   * Method: Deletes a specific InvolvedPerson addressed by the given primary identifier. Returns false on failure or if no target record was found, otherwise true.
   */
  public class DeleteInvolvedPersonByInvolvedPersonUidResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string { get; set; } = null;
    
    // Return-Value of 'DeleteInvolvedPersonByInvolvedPersonUid' (Boolean)
    public @return : bool { get; set; }
    
  }
  
  /**
   * Contains arguments for calling 'GetInvolvementRoleByInvolvedPersonRoleUid'.
   * Method: Loads a specific InvolvementRole addressed by the given primary identifier. Returns null on failure, or if no record exists with the given identity.
   */
  public class GetInvolvementRoleByInvolvedPersonRoleUidRequest {
    
    // Required Argument for 'GetInvolvementRoleByInvolvedPersonRoleUid' (string): An <see href="https://de.wikipedia.org/wiki/Universally_Unique_Identifier">Universally Unique Identifier</see> which can be generated by any origin system and is used to address this ORSCF conform data record in decentralized environments. Note that this Identity must not be changed any more!
    [Required]
    public involvedPersonRoleUid : string { get; set; }
    
  }
  
  /**
   * Contains results from calling 'GetInvolvementRoleByInvolvedPersonRoleUid'.
   * Method: Loads a specific InvolvementRole addressed by the given primary identifier. Returns null on failure, or if no record exists with the given identity.
   */
  public class GetInvolvementRoleByInvolvedPersonRoleUidResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string { get; set; } = null;
    
    // Return-Value of 'GetInvolvementRoleByInvolvedPersonRoleUid' (InvolvementRole)
    public @return : InvolvementRole { get; set; }
    
  }
  
  /**
   * Contains arguments for calling 'GetInvolvementRoles'.
   * Method: Loads InvolvementRoles.
   */
  public class GetInvolvementRolesRequest {
    
    // Optional Argument for 'GetInvolvementRoles' (number?): Number of the page, which should be returned
    public page : number? { get; set; } = null;
    
    // Optional Argument for 'GetInvolvementRoles' (number?): Max count of InvolvementRoles which should be returned
    public pageSize : number? { get; set; } = null;
    
  }
  
  /**
   * Contains results from calling 'GetInvolvementRoles'.
   * Method: Loads InvolvementRoles.
   */
  public class GetInvolvementRolesResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string { get; set; } = null;
    
    // Return-Value of 'GetInvolvementRoles' (InvolvementRole[])
    public @return : InvolvementRole[] { get; set; }
    
  }
  
  /**
   * Contains arguments for calling 'SearchInvolvementRoles'.
   * Method: Loads InvolvementRoles where values matching to the given filterExpression
   */
  public class SearchInvolvementRolesRequest {
    
    // Required Argument for 'SearchInvolvementRoles' (string): a filter expression like '((FieldName1 == "ABC" &amp;&amp; FieldName2 &gt; 12) || FieldName2 != "")'
    [Required]
    public filterExpression : string { get; set; }
    
    // Optional Argument for 'SearchInvolvementRoles' (string): one or more property names which are used as sort order (before pagination)
    public sortingExpression : string { get; set; }
    
    // Optional Argument for 'SearchInvolvementRoles' (number?): Number of the page, which should be returned
    public page : number? { get; set; } = null;
    
    // Optional Argument for 'SearchInvolvementRoles' (number?): Max count of InvolvementRoles which should be returned
    public pageSize : number? { get; set; } = null;
    
  }
  
  /**
   * Contains results from calling 'SearchInvolvementRoles'.
   * Method: Loads InvolvementRoles where values matching to the given filterExpression
   */
  public class SearchInvolvementRolesResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string { get; set; } = null;
    
    // Return-Value of 'SearchInvolvementRoles' (InvolvementRole[])
    public @return : InvolvementRole[] { get; set; }
    
  }
  
  /**
   * Contains arguments for calling 'AddNewInvolvementRole'.
   * Method: Adds a new InvolvementRole and returns its primary identifier (or null on failure).
   */
  public class AddNewInvolvementRoleRequest {
    
    // Required Argument for 'AddNewInvolvementRole' (InvolvementRole): InvolvementRole containing the new values
    [Required]
    public involvementRole : InvolvementRole { get; set; }
    
  }
  
  /**
   * Contains results from calling 'AddNewInvolvementRole'.
   * Method: Adds a new InvolvementRole and returns its primary identifier (or null on failure).
   */
  public class AddNewInvolvementRoleResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string { get; set; } = null;
    
    // Return-Value of 'AddNewInvolvementRole' (Boolean)
    public @return : bool { get; set; }
    
  }
  
  /**
   * Contains arguments for calling 'UpdateInvolvementRole'.
   * Method: Updates all values (which are not "FixedAfterCreation") of the given InvolvementRole addressed by the primary identifier fields within the given InvolvementRole. Returns false on failure or if no target record was found, otherwise true.
   */
  public class UpdateInvolvementRoleRequest {
    
    // Required Argument for 'UpdateInvolvementRole' (InvolvementRole): InvolvementRole containing the new values (the primary identifier fields within the given InvolvementRole will be used to address the target record)
    [Required]
    public involvementRole : InvolvementRole { get; set; }
    
  }
  
  /**
   * Contains results from calling 'UpdateInvolvementRole'.
   * Method: Updates all values (which are not "FixedAfterCreation") of the given InvolvementRole addressed by the primary identifier fields within the given InvolvementRole. Returns false on failure or if no target record was found, otherwise true.
   */
  public class UpdateInvolvementRoleResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string { get; set; } = null;
    
    // Return-Value of 'UpdateInvolvementRole' (Boolean)
    public @return : bool { get; set; }
    
  }
  
  /**
   * Contains arguments for calling 'UpdateInvolvementRoleByInvolvedPersonRoleUid'.
   * Method: Updates all values (which are not "FixedAfterCreation") of the given InvolvementRole addressed by the supplementary given primary identifier. Returns false on failure or if no target record was found, otherwise true.
   */
  public class UpdateInvolvementRoleByInvolvedPersonRoleUidRequest {
    
    // Required Argument for 'UpdateInvolvementRoleByInvolvedPersonRoleUid' (string): An <see href="https://de.wikipedia.org/wiki/Universally_Unique_Identifier">Universally Unique Identifier</see> which can be generated by any origin system and is used to address this ORSCF conform data record in decentralized environments. Note that this Identity must not be changed any more!
    [Required]
    public involvedPersonRoleUid : string { get; set; }
    
    // Required Argument for 'UpdateInvolvementRoleByInvolvedPersonRoleUid' (InvolvementRole): InvolvementRole containing the new values (the primary identifier fields within the given InvolvementRole will be ignored)
    [Required]
    public involvementRole : InvolvementRole { get; set; }
    
  }
  
  /**
   * Contains results from calling 'UpdateInvolvementRoleByInvolvedPersonRoleUid'.
   * Method: Updates all values (which are not "FixedAfterCreation") of the given InvolvementRole addressed by the supplementary given primary identifier. Returns false on failure or if no target record was found, otherwise true.
   */
  public class UpdateInvolvementRoleByInvolvedPersonRoleUidResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string { get; set; } = null;
    
    // Return-Value of 'UpdateInvolvementRoleByInvolvedPersonRoleUid' (Boolean)
    public @return : bool { get; set; }
    
  }
  
  /**
   * Contains arguments for calling 'DeleteInvolvementRoleByInvolvedPersonRoleUid'.
   * Method: Deletes a specific InvolvementRole addressed by the given primary identifier. Returns false on failure or if no target record was found, otherwise true.
   */
  public class DeleteInvolvementRoleByInvolvedPersonRoleUidRequest {
    
    // Required Argument for 'DeleteInvolvementRoleByInvolvedPersonRoleUid' (string): An <see href="https://de.wikipedia.org/wiki/Universally_Unique_Identifier">Universally Unique Identifier</see> which can be generated by any origin system and is used to address this ORSCF conform data record in decentralized environments. Note that this Identity must not be changed any more!
    [Required]
    public involvedPersonRoleUid : string { get; set; }
    
  }
  
  /**
   * Contains results from calling 'DeleteInvolvementRoleByInvolvedPersonRoleUid'.
   * Method: Deletes a specific InvolvementRole addressed by the given primary identifier. Returns false on failure or if no target record was found, otherwise true.
   */
  public class DeleteInvolvementRoleByInvolvedPersonRoleUidResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string { get; set; } = null;
    
    // Return-Value of 'DeleteInvolvementRoleByInvolvedPersonRoleUid' (Boolean)
    public @return : bool { get; set; }
    
  }
  
  /**
   * Contains arguments for calling 'GetStudyRelatedSystemAssignmentByStudyRelatedSystemAssignmentUid'.
   * Method: Loads a specific StudyRelatedSystemAssignment addressed by the given primary identifier. Returns null on failure, or if no record exists with the given identity.
   */
  public class GetStudyRelatedSystemAssignmentByStudyRelatedSystemAssignmentUidRequest {
    
    // Required Argument for 'GetStudyRelatedSystemAssignmentByStudyRelatedSystemAssignmentUid' (string): Represents the primary identity of a StudyRelatedSystemAssignment
    [Required]
    public studyRelatedSystemAssignmentUid : string { get; set; }
    
  }
  
  /**
   * Contains results from calling 'GetStudyRelatedSystemAssignmentByStudyRelatedSystemAssignmentUid'.
   * Method: Loads a specific StudyRelatedSystemAssignment addressed by the given primary identifier. Returns null on failure, or if no record exists with the given identity.
   */
  public class GetStudyRelatedSystemAssignmentByStudyRelatedSystemAssignmentUidResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string { get; set; } = null;
    
    // Return-Value of 'GetStudyRelatedSystemAssignmentByStudyRelatedSystemAssignmentUid' (StudyRelatedSystemAssignment)
    public @return : StudyRelatedSystemAssignment { get; set; }
    
  }
  
  /**
   * Contains arguments for calling 'GetStudyRelatedSystemAssignments'.
   * Method: Loads StudyRelatedSystemAssignments.
   */
  public class GetStudyRelatedSystemAssignmentsRequest {
    
    // Optional Argument for 'GetStudyRelatedSystemAssignments' (number?): Number of the page, which should be returned
    public page : number? { get; set; } = null;
    
    // Optional Argument for 'GetStudyRelatedSystemAssignments' (number?): Max count of StudyRelatedSystemAssignments which should be returned
    public pageSize : number? { get; set; } = null;
    
  }
  
  /**
   * Contains results from calling 'GetStudyRelatedSystemAssignments'.
   * Method: Loads StudyRelatedSystemAssignments.
   */
  public class GetStudyRelatedSystemAssignmentsResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string { get; set; } = null;
    
    // Return-Value of 'GetStudyRelatedSystemAssignments' (StudyRelatedSystemAssignment[])
    public @return : StudyRelatedSystemAssignment[] { get; set; }
    
  }
  
  /**
   * Contains arguments for calling 'SearchStudyRelatedSystemAssignments'.
   * Method: Loads StudyRelatedSystemAssignments where values matching to the given filterExpression
   */
  public class SearchStudyRelatedSystemAssignmentsRequest {
    
    // Required Argument for 'SearchStudyRelatedSystemAssignments' (string): a filter expression like '((FieldName1 == "ABC" &amp;&amp; FieldName2 &gt; 12) || FieldName2 != "")'
    [Required]
    public filterExpression : string { get; set; }
    
    // Optional Argument for 'SearchStudyRelatedSystemAssignments' (string): one or more property names which are used as sort order (before pagination)
    public sortingExpression : string { get; set; }
    
    // Optional Argument for 'SearchStudyRelatedSystemAssignments' (number?): Number of the page, which should be returned
    public page : number? { get; set; } = null;
    
    // Optional Argument for 'SearchStudyRelatedSystemAssignments' (number?): Max count of StudyRelatedSystemAssignments which should be returned
    public pageSize : number? { get; set; } = null;
    
  }
  
  /**
   * Contains results from calling 'SearchStudyRelatedSystemAssignments'.
   * Method: Loads StudyRelatedSystemAssignments where values matching to the given filterExpression
   */
  public class SearchStudyRelatedSystemAssignmentsResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string { get; set; } = null;
    
    // Return-Value of 'SearchStudyRelatedSystemAssignments' (StudyRelatedSystemAssignment[])
    public @return : StudyRelatedSystemAssignment[] { get; set; }
    
  }
  
  /**
   * Contains arguments for calling 'AddNewStudyRelatedSystemAssignment'.
   * Method: Adds a new StudyRelatedSystemAssignment and returns its primary identifier (or null on failure).
   */
  public class AddNewStudyRelatedSystemAssignmentRequest {
    
    // Required Argument for 'AddNewStudyRelatedSystemAssignment' (StudyRelatedSystemAssignment): StudyRelatedSystemAssignment containing the new values
    [Required]
    public studyRelatedSystemAssignment : StudyRelatedSystemAssignment { get; set; }
    
  }
  
  /**
   * Contains results from calling 'AddNewStudyRelatedSystemAssignment'.
   * Method: Adds a new StudyRelatedSystemAssignment and returns its primary identifier (or null on failure).
   */
  public class AddNewStudyRelatedSystemAssignmentResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string { get; set; } = null;
    
    // Return-Value of 'AddNewStudyRelatedSystemAssignment' (Boolean)
    public @return : bool { get; set; }
    
  }
  
  /**
   * Contains arguments for calling 'UpdateStudyRelatedSystemAssignment'.
   * Method: Updates all values (which are not "FixedAfterCreation") of the given StudyRelatedSystemAssignment addressed by the primary identifier fields within the given StudyRelatedSystemAssignment. Returns false on failure or if no target record was found, otherwise true.
   */
  public class UpdateStudyRelatedSystemAssignmentRequest {
    
    // Required Argument for 'UpdateStudyRelatedSystemAssignment' (StudyRelatedSystemAssignment): StudyRelatedSystemAssignment containing the new values (the primary identifier fields within the given StudyRelatedSystemAssignment will be used to address the target record)
    [Required]
    public studyRelatedSystemAssignment : StudyRelatedSystemAssignment { get; set; }
    
  }
  
  /**
   * Contains results from calling 'UpdateStudyRelatedSystemAssignment'.
   * Method: Updates all values (which are not "FixedAfterCreation") of the given StudyRelatedSystemAssignment addressed by the primary identifier fields within the given StudyRelatedSystemAssignment. Returns false on failure or if no target record was found, otherwise true.
   */
  public class UpdateStudyRelatedSystemAssignmentResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string { get; set; } = null;
    
    // Return-Value of 'UpdateStudyRelatedSystemAssignment' (Boolean)
    public @return : bool { get; set; }
    
  }
  
  /**
   * Contains arguments for calling 'UpdateStudyRelatedSystemAssignmentByStudyRelatedSystemAssignmentUid'.
   * Method: Updates all values (which are not "FixedAfterCreation") of the given StudyRelatedSystemAssignment addressed by the supplementary given primary identifier. Returns false on failure or if no target record was found, otherwise true.
   */
  public class UpdateStudyRelatedSystemAssignmentByStudyRelatedSystemAssignmentUidRequest {
    
    // Required Argument for 'UpdateStudyRelatedSystemAssignmentByStudyRelatedSystemAssignmentUid' (string): Represents the primary identity of a StudyRelatedSystemAssignment
    [Required]
    public studyRelatedSystemAssignmentUid : string { get; set; }
    
    // Required Argument for 'UpdateStudyRelatedSystemAssignmentByStudyRelatedSystemAssignmentUid' (StudyRelatedSystemAssignment): StudyRelatedSystemAssignment containing the new values (the primary identifier fields within the given StudyRelatedSystemAssignment will be ignored)
    [Required]
    public studyRelatedSystemAssignment : StudyRelatedSystemAssignment { get; set; }
    
  }
  
  /**
   * Contains results from calling 'UpdateStudyRelatedSystemAssignmentByStudyRelatedSystemAssignmentUid'.
   * Method: Updates all values (which are not "FixedAfterCreation") of the given StudyRelatedSystemAssignment addressed by the supplementary given primary identifier. Returns false on failure or if no target record was found, otherwise true.
   */
  public class UpdateStudyRelatedSystemAssignmentByStudyRelatedSystemAssignmentUidResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string { get; set; } = null;
    
    // Return-Value of 'UpdateStudyRelatedSystemAssignmentByStudyRelatedSystemAssignmentUid' (Boolean)
    public @return : bool { get; set; }
    
  }
  
  /**
   * Contains arguments for calling 'DeleteStudyRelatedSystemAssignmentByStudyRelatedSystemAssignmentUid'.
   * Method: Deletes a specific StudyRelatedSystemAssignment addressed by the given primary identifier. Returns false on failure or if no target record was found, otherwise true.
   */
  public class DeleteStudyRelatedSystemAssignmentByStudyRelatedSystemAssignmentUidRequest {
    
    // Required Argument for 'DeleteStudyRelatedSystemAssignmentByStudyRelatedSystemAssignmentUid' (string): Represents the primary identity of a StudyRelatedSystemAssignment
    [Required]
    public studyRelatedSystemAssignmentUid : string { get; set; }
    
  }
  
  /**
   * Contains results from calling 'DeleteStudyRelatedSystemAssignmentByStudyRelatedSystemAssignmentUid'.
   * Method: Deletes a specific StudyRelatedSystemAssignment addressed by the given primary identifier. Returns false on failure or if no target record was found, otherwise true.
   */
  public class DeleteStudyRelatedSystemAssignmentByStudyRelatedSystemAssignmentUidResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string { get; set; } = null;
    
    // Return-Value of 'DeleteStudyRelatedSystemAssignmentByStudyRelatedSystemAssignmentUid' (Boolean)
    public @return : bool { get; set; }
    
  }
  
  /**
   * Contains arguments for calling 'GetSiteRelatedSystemAssignmentBySiteRelatedSystemAssignmentUid'.
   * Method: Loads a specific SiteRelatedSystemAssignment addressed by the given primary identifier. Returns null on failure, or if no record exists with the given identity.
   */
  public class GetSiteRelatedSystemAssignmentBySiteRelatedSystemAssignmentUidRequest {
    
    // Required Argument for 'GetSiteRelatedSystemAssignmentBySiteRelatedSystemAssignmentUid' (string): Represents the primary identity of a SiteRelatedSystemAssignment
    [Required]
    public siteRelatedSystemAssignmentUid : string { get; set; }
    
  }
  
  /**
   * Contains results from calling 'GetSiteRelatedSystemAssignmentBySiteRelatedSystemAssignmentUid'.
   * Method: Loads a specific SiteRelatedSystemAssignment addressed by the given primary identifier. Returns null on failure, or if no record exists with the given identity.
   */
  public class GetSiteRelatedSystemAssignmentBySiteRelatedSystemAssignmentUidResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string { get; set; } = null;
    
    // Return-Value of 'GetSiteRelatedSystemAssignmentBySiteRelatedSystemAssignmentUid' (SiteRelatedSystemAssignment)
    public @return : SiteRelatedSystemAssignment { get; set; }
    
  }
  
  /**
   * Contains arguments for calling 'GetSiteRelatedSystemAssignments'.
   * Method: Loads SiteRelatedSystemAssignments.
   */
  public class GetSiteRelatedSystemAssignmentsRequest {
    
    // Optional Argument for 'GetSiteRelatedSystemAssignments' (number?): Number of the page, which should be returned
    public page : number? { get; set; } = null;
    
    // Optional Argument for 'GetSiteRelatedSystemAssignments' (number?): Max count of SiteRelatedSystemAssignments which should be returned
    public pageSize : number? { get; set; } = null;
    
  }
  
  /**
   * Contains results from calling 'GetSiteRelatedSystemAssignments'.
   * Method: Loads SiteRelatedSystemAssignments.
   */
  public class GetSiteRelatedSystemAssignmentsResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string { get; set; } = null;
    
    // Return-Value of 'GetSiteRelatedSystemAssignments' (SiteRelatedSystemAssignment[])
    public @return : SiteRelatedSystemAssignment[] { get; set; }
    
  }
  
  /**
   * Contains arguments for calling 'SearchSiteRelatedSystemAssignments'.
   * Method: Loads SiteRelatedSystemAssignments where values matching to the given filterExpression
   */
  public class SearchSiteRelatedSystemAssignmentsRequest {
    
    // Required Argument for 'SearchSiteRelatedSystemAssignments' (string): a filter expression like '((FieldName1 == "ABC" &amp;&amp; FieldName2 &gt; 12) || FieldName2 != "")'
    [Required]
    public filterExpression : string { get; set; }
    
    // Optional Argument for 'SearchSiteRelatedSystemAssignments' (string): one or more property names which are used as sort order (before pagination)
    public sortingExpression : string { get; set; }
    
    // Optional Argument for 'SearchSiteRelatedSystemAssignments' (number?): Number of the page, which should be returned
    public page : number? { get; set; } = null;
    
    // Optional Argument for 'SearchSiteRelatedSystemAssignments' (number?): Max count of SiteRelatedSystemAssignments which should be returned
    public pageSize : number? { get; set; } = null;
    
  }
  
  /**
   * Contains results from calling 'SearchSiteRelatedSystemAssignments'.
   * Method: Loads SiteRelatedSystemAssignments where values matching to the given filterExpression
   */
  public class SearchSiteRelatedSystemAssignmentsResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string { get; set; } = null;
    
    // Return-Value of 'SearchSiteRelatedSystemAssignments' (SiteRelatedSystemAssignment[])
    public @return : SiteRelatedSystemAssignment[] { get; set; }
    
  }
  
  /**
   * Contains arguments for calling 'AddNewSiteRelatedSystemAssignment'.
   * Method: Adds a new SiteRelatedSystemAssignment and returns its primary identifier (or null on failure).
   */
  public class AddNewSiteRelatedSystemAssignmentRequest {
    
    // Required Argument for 'AddNewSiteRelatedSystemAssignment' (SiteRelatedSystemAssignment): SiteRelatedSystemAssignment containing the new values
    [Required]
    public siteRelatedSystemAssignment : SiteRelatedSystemAssignment { get; set; }
    
  }
  
  /**
   * Contains results from calling 'AddNewSiteRelatedSystemAssignment'.
   * Method: Adds a new SiteRelatedSystemAssignment and returns its primary identifier (or null on failure).
   */
  public class AddNewSiteRelatedSystemAssignmentResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string { get; set; } = null;
    
    // Return-Value of 'AddNewSiteRelatedSystemAssignment' (Boolean)
    public @return : bool { get; set; }
    
  }
  
  /**
   * Contains arguments for calling 'UpdateSiteRelatedSystemAssignment'.
   * Method: Updates all values (which are not "FixedAfterCreation") of the given SiteRelatedSystemAssignment addressed by the primary identifier fields within the given SiteRelatedSystemAssignment. Returns false on failure or if no target record was found, otherwise true.
   */
  public class UpdateSiteRelatedSystemAssignmentRequest {
    
    // Required Argument for 'UpdateSiteRelatedSystemAssignment' (SiteRelatedSystemAssignment): SiteRelatedSystemAssignment containing the new values (the primary identifier fields within the given SiteRelatedSystemAssignment will be used to address the target record)
    [Required]
    public siteRelatedSystemAssignment : SiteRelatedSystemAssignment { get; set; }
    
  }
  
  /**
   * Contains results from calling 'UpdateSiteRelatedSystemAssignment'.
   * Method: Updates all values (which are not "FixedAfterCreation") of the given SiteRelatedSystemAssignment addressed by the primary identifier fields within the given SiteRelatedSystemAssignment. Returns false on failure or if no target record was found, otherwise true.
   */
  public class UpdateSiteRelatedSystemAssignmentResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string { get; set; } = null;
    
    // Return-Value of 'UpdateSiteRelatedSystemAssignment' (Boolean)
    public @return : bool { get; set; }
    
  }
  
  /**
   * Contains arguments for calling 'UpdateSiteRelatedSystemAssignmentBySiteRelatedSystemAssignmentUid'.
   * Method: Updates all values (which are not "FixedAfterCreation") of the given SiteRelatedSystemAssignment addressed by the supplementary given primary identifier. Returns false on failure or if no target record was found, otherwise true.
   */
  public class UpdateSiteRelatedSystemAssignmentBySiteRelatedSystemAssignmentUidRequest {
    
    // Required Argument for 'UpdateSiteRelatedSystemAssignmentBySiteRelatedSystemAssignmentUid' (string): Represents the primary identity of a SiteRelatedSystemAssignment
    [Required]
    public siteRelatedSystemAssignmentUid : string { get; set; }
    
    // Required Argument for 'UpdateSiteRelatedSystemAssignmentBySiteRelatedSystemAssignmentUid' (SiteRelatedSystemAssignment): SiteRelatedSystemAssignment containing the new values (the primary identifier fields within the given SiteRelatedSystemAssignment will be ignored)
    [Required]
    public siteRelatedSystemAssignment : SiteRelatedSystemAssignment { get; set; }
    
  }
  
  /**
   * Contains results from calling 'UpdateSiteRelatedSystemAssignmentBySiteRelatedSystemAssignmentUid'.
   * Method: Updates all values (which are not "FixedAfterCreation") of the given SiteRelatedSystemAssignment addressed by the supplementary given primary identifier. Returns false on failure or if no target record was found, otherwise true.
   */
  public class UpdateSiteRelatedSystemAssignmentBySiteRelatedSystemAssignmentUidResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string { get; set; } = null;
    
    // Return-Value of 'UpdateSiteRelatedSystemAssignmentBySiteRelatedSystemAssignmentUid' (Boolean)
    public @return : bool { get; set; }
    
  }
  
  /**
   * Contains arguments for calling 'DeleteSiteRelatedSystemAssignmentBySiteRelatedSystemAssignmentUid'.
   * Method: Deletes a specific SiteRelatedSystemAssignment addressed by the given primary identifier. Returns false on failure or if no target record was found, otherwise true.
   */
  public class DeleteSiteRelatedSystemAssignmentBySiteRelatedSystemAssignmentUidRequest {
    
    // Required Argument for 'DeleteSiteRelatedSystemAssignmentBySiteRelatedSystemAssignmentUid' (string): Represents the primary identity of a SiteRelatedSystemAssignment
    [Required]
    public siteRelatedSystemAssignmentUid : string { get; set; }
    
  }
  
  /**
   * Contains results from calling 'DeleteSiteRelatedSystemAssignmentBySiteRelatedSystemAssignmentUid'.
   * Method: Deletes a specific SiteRelatedSystemAssignment addressed by the given primary identifier. Returns false on failure or if no target record was found, otherwise true.
   */
  public class DeleteSiteRelatedSystemAssignmentBySiteRelatedSystemAssignmentUidResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string { get; set; } = null;
    
    // Return-Value of 'DeleteSiteRelatedSystemAssignmentBySiteRelatedSystemAssignmentUid' (Boolean)
    public @return : bool { get; set; }
    
  }
  
}
