/* based on ORSCF StudyManagement Contract v1.7.0.0 */

import MedicalResearch.StudyManagement.Model;

namespace MedicalResearch.StudyManagement.StoreAccess {
  
  /**
   * Contains arguments for calling 'GetInstituteByInstituteUid'.
   * Method: Loads a specific Institute addressed by the given primary identifier. Returns null on failure, or if no record exists with the given identity.
   */
  export class GetInstituteByInstituteUidRequest {
    
    // Required Argument for 'GetInstituteByInstituteUid' (string): An <see href="https://de.wikipedia.org/wiki/Universally_Unique_Identifier">Universally Unique Identifier</see> which can be generated by any origin system and is used to address this ORSCF conform data record in decentralized environments. Note that this Identity must not be changed any more!
    public instituteUid : string;
    
  }
  
  /**
   * Contains results from calling 'GetInstituteByInstituteUid'.
   * Method: Loads a specific Institute addressed by the given primary identifier. Returns null on failure, or if no record exists with the given identity.
   */
  export class GetInstituteByInstituteUidResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string = null;
    
    // Return-Value of 'GetInstituteByInstituteUid' (Institute)
    public return : Institute;
    
  }
  
  /**
   * Contains arguments for calling 'GetInstitutes'.
   * Method: Loads Institutes.
   */
  export class GetInstitutesRequest {
    
    // Optional Argument for 'GetInstitutes' (number): Number of the page, which should be returned
    public page? : number = null;
    
    // Optional Argument for 'GetInstitutes' (number): Max count of Institutes which should be returned
    public pageSize? : number = null;
    
  }
  
  /**
   * Contains results from calling 'GetInstitutes'.
   * Method: Loads Institutes.
   */
  export class GetInstitutesResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string = null;
    
    // Return-Value of 'GetInstitutes' (Institute[])
    public return : Institute[];
    
  }
  
  /**
   * Contains arguments for calling 'SearchInstitutes'.
   * Method: Loads Institutes where values matching to the given filterExpression
   */
  export class SearchInstitutesRequest {
    
    // Required Argument for 'SearchInstitutes' (string): a filter expression like '((FieldName1 == "ABC" &amp;&amp; FieldName2 &gt; 12) || FieldName2 != "")'
    public filterExpression : string;
    
    // Optional Argument for 'SearchInstitutes' (string): one or more property names which are used as sort order (before pagination)
    public sortingExpression? : string;
    
    // Optional Argument for 'SearchInstitutes' (number): Number of the page, which should be returned
    public page? : number = null;
    
    // Optional Argument for 'SearchInstitutes' (number): Max count of Institutes which should be returned
    public pageSize? : number = null;
    
  }
  
  /**
   * Contains results from calling 'SearchInstitutes'.
   * Method: Loads Institutes where values matching to the given filterExpression
   */
  export class SearchInstitutesResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string = null;
    
    // Return-Value of 'SearchInstitutes' (Institute[])
    public return : Institute[];
    
  }
  
  /**
   * Contains arguments for calling 'AddNewInstitute'.
   * Method: Adds a new Institute and returns its primary identifier (or null on failure).
   */
  export class AddNewInstituteRequest {
    
    // Required Argument for 'AddNewInstitute' (Institute): Institute containing the new values
    public institute : Institute;
    
  }
  
  /**
   * Contains results from calling 'AddNewInstitute'.
   * Method: Adds a new Institute and returns its primary identifier (or null on failure).
   */
  export class AddNewInstituteResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string = null;
    
    // Return-Value of 'AddNewInstitute' (Boolean)
    public return : boolean;
    
  }
  
  /**
   * Contains arguments for calling 'UpdateInstitute'.
   * Method: Updates all values (which are not "FixedAfterCreation") of the given Institute addressed by the primary identifier fields within the given Institute. Returns false on failure or if no target record was found, otherwise true.
   */
  export class UpdateInstituteRequest {
    
    // Required Argument for 'UpdateInstitute' (Institute): Institute containing the new values (the primary identifier fields within the given Institute will be used to address the target record)
    public institute : Institute;
    
  }
  
  /**
   * Contains results from calling 'UpdateInstitute'.
   * Method: Updates all values (which are not "FixedAfterCreation") of the given Institute addressed by the primary identifier fields within the given Institute. Returns false on failure or if no target record was found, otherwise true.
   */
  export class UpdateInstituteResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string = null;
    
    // Return-Value of 'UpdateInstitute' (Boolean)
    public return : boolean;
    
  }
  
  /**
   * Contains arguments for calling 'UpdateInstituteByInstituteUid'.
   * Method: Updates all values (which are not "FixedAfterCreation") of the given Institute addressed by the supplementary given primary identifier. Returns false on failure or if no target record was found, otherwise true.
   */
  export class UpdateInstituteByInstituteUidRequest {
    
    // Required Argument for 'UpdateInstituteByInstituteUid' (string): An <see href="https://de.wikipedia.org/wiki/Universally_Unique_Identifier">Universally Unique Identifier</see> which can be generated by any origin system and is used to address this ORSCF conform data record in decentralized environments. Note that this Identity must not be changed any more!
    public instituteUid : string;
    
    // Required Argument for 'UpdateInstituteByInstituteUid' (Institute): Institute containing the new values (the primary identifier fields within the given Institute will be ignored)
    public institute : Institute;
    
  }
  
  /**
   * Contains results from calling 'UpdateInstituteByInstituteUid'.
   * Method: Updates all values (which are not "FixedAfterCreation") of the given Institute addressed by the supplementary given primary identifier. Returns false on failure or if no target record was found, otherwise true.
   */
  export class UpdateInstituteByInstituteUidResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string = null;
    
    // Return-Value of 'UpdateInstituteByInstituteUid' (Boolean)
    public return : boolean;
    
  }
  
  /**
   * Contains arguments for calling 'DeleteInstituteByInstituteUid'.
   * Method: Deletes a specific Institute addressed by the given primary identifier. Returns false on failure or if no target record was found, otherwise true.
   */
  export class DeleteInstituteByInstituteUidRequest {
    
    // Required Argument for 'DeleteInstituteByInstituteUid' (string): An <see href="https://de.wikipedia.org/wiki/Universally_Unique_Identifier">Universally Unique Identifier</see> which can be generated by any origin system and is used to address this ORSCF conform data record in decentralized environments. Note that this Identity must not be changed any more!
    public instituteUid : string;
    
  }
  
  /**
   * Contains results from calling 'DeleteInstituteByInstituteUid'.
   * Method: Deletes a specific Institute addressed by the given primary identifier. Returns false on failure or if no target record was found, otherwise true.
   */
  export class DeleteInstituteByInstituteUidResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string = null;
    
    // Return-Value of 'DeleteInstituteByInstituteUid' (Boolean)
    public return : boolean;
    
  }
  
  /**
   * Contains arguments for calling 'GetResearchStudyByResearchStudyUid'.
   * Method: Loads a specific ResearchStudy addressed by the given primary identifier. Returns null on failure, or if no record exists with the given identity.
   */
  export class GetResearchStudyByResearchStudyUidRequest {
    
    // Required Argument for 'GetResearchStudyByResearchStudyUid' (string): An <see href="https://de.wikipedia.org/wiki/Universally_Unique_Identifier">Universally Unique Identifier</see> which can be generated by any origin system and is used to address this ORSCF conform data record in decentralized environments. Note that this Identity must not be changed any more!
    public researchStudyUid : string;
    
  }
  
  /**
   * Contains results from calling 'GetResearchStudyByResearchStudyUid'.
   * Method: Loads a specific ResearchStudy addressed by the given primary identifier. Returns null on failure, or if no record exists with the given identity.
   */
  export class GetResearchStudyByResearchStudyUidResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string = null;
    
    // Return-Value of 'GetResearchStudyByResearchStudyUid' (ResearchStudy): entity, which relates to <see href="https://www.hl7.org/fhir/researchstudy.html">HL7.ResearchStudy</see>
    public return : ResearchStudy;
    
  }
  
  /**
   * Contains arguments for calling 'GetResearchStudies'.
   * Method: Loads ResearchStudies.
   */
  export class GetResearchStudiesRequest {
    
    // Optional Argument for 'GetResearchStudies' (number): Number of the page, which should be returned
    public page? : number = null;
    
    // Optional Argument for 'GetResearchStudies' (number): Max count of ResearchStudies which should be returned
    public pageSize? : number = null;
    
  }
  
  /**
   * Contains results from calling 'GetResearchStudies'.
   * Method: Loads ResearchStudies.
   */
  export class GetResearchStudiesResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string = null;
    
    // Return-Value of 'GetResearchStudies' (ResearchStudy[]): entity, which relates to <see href="https://www.hl7.org/fhir/researchstudy.html">HL7.ResearchStudy</see>
    public return : ResearchStudy[];
    
  }
  
  /**
   * Contains arguments for calling 'SearchResearchStudies'.
   * Method: Loads ResearchStudies where values matching to the given filterExpression
   */
  export class SearchResearchStudiesRequest {
    
    // Required Argument for 'SearchResearchStudies' (string): a filter expression like '((FieldName1 == "ABC" &amp;&amp; FieldName2 &gt; 12) || FieldName2 != "")'
    public filterExpression : string;
    
    // Optional Argument for 'SearchResearchStudies' (string): one or more property names which are used as sort order (before pagination)
    public sortingExpression? : string;
    
    // Optional Argument for 'SearchResearchStudies' (number): Number of the page, which should be returned
    public page? : number = null;
    
    // Optional Argument for 'SearchResearchStudies' (number): Max count of ResearchStudies which should be returned
    public pageSize? : number = null;
    
  }
  
  /**
   * Contains results from calling 'SearchResearchStudies'.
   * Method: Loads ResearchStudies where values matching to the given filterExpression
   */
  export class SearchResearchStudiesResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string = null;
    
    // Return-Value of 'SearchResearchStudies' (ResearchStudy[]): entity, which relates to <see href="https://www.hl7.org/fhir/researchstudy.html">HL7.ResearchStudy</see>
    public return : ResearchStudy[];
    
  }
  
  /**
   * Contains arguments for calling 'AddNewResearchStudy'.
   * Method: Adds a new ResearchStudy and returns its primary identifier (or null on failure).
   */
  export class AddNewResearchStudyRequest {
    
    // Required Argument for 'AddNewResearchStudy' (ResearchStudy): ResearchStudy containing the new values
    public researchStudy : ResearchStudy;
    
  }
  
  /**
   * Contains results from calling 'AddNewResearchStudy'.
   * Method: Adds a new ResearchStudy and returns its primary identifier (or null on failure).
   */
  export class AddNewResearchStudyResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string = null;
    
    // Return-Value of 'AddNewResearchStudy' (Boolean)
    public return : boolean;
    
  }
  
  /**
   * Contains arguments for calling 'UpdateResearchStudy'.
   * Method: Updates all values (which are not "FixedAfterCreation") of the given ResearchStudy addressed by the primary identifier fields within the given ResearchStudy. Returns false on failure or if no target record was found, otherwise true.
   */
  export class UpdateResearchStudyRequest {
    
    // Required Argument for 'UpdateResearchStudy' (ResearchStudy): ResearchStudy containing the new values (the primary identifier fields within the given ResearchStudy will be used to address the target record)
    public researchStudy : ResearchStudy;
    
  }
  
  /**
   * Contains results from calling 'UpdateResearchStudy'.
   * Method: Updates all values (which are not "FixedAfterCreation") of the given ResearchStudy addressed by the primary identifier fields within the given ResearchStudy. Returns false on failure or if no target record was found, otherwise true.
   */
  export class UpdateResearchStudyResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string = null;
    
    // Return-Value of 'UpdateResearchStudy' (Boolean)
    public return : boolean;
    
  }
  
  /**
   * Contains arguments for calling 'UpdateResearchStudyByResearchStudyUid'.
   * Method: Updates all values (which are not "FixedAfterCreation") of the given ResearchStudy addressed by the supplementary given primary identifier. Returns false on failure or if no target record was found, otherwise true.
   */
  export class UpdateResearchStudyByResearchStudyUidRequest {
    
    // Required Argument for 'UpdateResearchStudyByResearchStudyUid' (string): An <see href="https://de.wikipedia.org/wiki/Universally_Unique_Identifier">Universally Unique Identifier</see> which can be generated by any origin system and is used to address this ORSCF conform data record in decentralized environments. Note that this Identity must not be changed any more!
    public researchStudyUid : string;
    
    // Required Argument for 'UpdateResearchStudyByResearchStudyUid' (ResearchStudy): ResearchStudy containing the new values (the primary identifier fields within the given ResearchStudy will be ignored)
    public researchStudy : ResearchStudy;
    
  }
  
  /**
   * Contains results from calling 'UpdateResearchStudyByResearchStudyUid'.
   * Method: Updates all values (which are not "FixedAfterCreation") of the given ResearchStudy addressed by the supplementary given primary identifier. Returns false on failure or if no target record was found, otherwise true.
   */
  export class UpdateResearchStudyByResearchStudyUidResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string = null;
    
    // Return-Value of 'UpdateResearchStudyByResearchStudyUid' (Boolean)
    public return : boolean;
    
  }
  
  /**
   * Contains arguments for calling 'DeleteResearchStudyByResearchStudyUid'.
   * Method: Deletes a specific ResearchStudy addressed by the given primary identifier. Returns false on failure or if no target record was found, otherwise true.
   */
  export class DeleteResearchStudyByResearchStudyUidRequest {
    
    // Required Argument for 'DeleteResearchStudyByResearchStudyUid' (string): An <see href="https://de.wikipedia.org/wiki/Universally_Unique_Identifier">Universally Unique Identifier</see> which can be generated by any origin system and is used to address this ORSCF conform data record in decentralized environments. Note that this Identity must not be changed any more!
    public researchStudyUid : string;
    
  }
  
  /**
   * Contains results from calling 'DeleteResearchStudyByResearchStudyUid'.
   * Method: Deletes a specific ResearchStudy addressed by the given primary identifier. Returns false on failure or if no target record was found, otherwise true.
   */
  export class DeleteResearchStudyByResearchStudyUidResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string = null;
    
    // Return-Value of 'DeleteResearchStudyByResearchStudyUid' (Boolean)
    public return : boolean;
    
  }
  
  /**
   * Contains arguments for calling 'GetSiteBySiteUid'.
   * Method: Loads a specific Site addressed by the given primary identifier. Returns null on failure, or if no record exists with the given identity.
   */
  export class GetSiteBySiteUidRequest {
    
    // Required Argument for 'GetSiteBySiteUid' (string): An <see href="https://de.wikipedia.org/wiki/Universally_Unique_Identifier">Universally Unique Identifier</see> which can be generated by any origin system and is used to address this ORSCF conform data record in decentralized environments. Note that this Identity must not be changed any more!
    public siteUid : string;
    
  }
  
  /**
   * Contains results from calling 'GetSiteBySiteUid'.
   * Method: Loads a specific Site addressed by the given primary identifier. Returns null on failure, or if no record exists with the given identity.
   */
  export class GetSiteBySiteUidResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string = null;
    
    // Return-Value of 'GetSiteBySiteUid' (Site)
    public return : Site;
    
  }
  
  /**
   * Contains arguments for calling 'GetSites'.
   * Method: Loads Sites.
   */
  export class GetSitesRequest {
    
    // Optional Argument for 'GetSites' (number): Number of the page, which should be returned
    public page? : number = null;
    
    // Optional Argument for 'GetSites' (number): Max count of Sites which should be returned
    public pageSize? : number = null;
    
  }
  
  /**
   * Contains results from calling 'GetSites'.
   * Method: Loads Sites.
   */
  export class GetSitesResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string = null;
    
    // Return-Value of 'GetSites' (Site[])
    public return : Site[];
    
  }
  
  /**
   * Contains arguments for calling 'SearchSites'.
   * Method: Loads Sites where values matching to the given filterExpression
   */
  export class SearchSitesRequest {
    
    // Required Argument for 'SearchSites' (string): a filter expression like '((FieldName1 == "ABC" &amp;&amp; FieldName2 &gt; 12) || FieldName2 != "")'
    public filterExpression : string;
    
    // Optional Argument for 'SearchSites' (string): one or more property names which are used as sort order (before pagination)
    public sortingExpression? : string;
    
    // Optional Argument for 'SearchSites' (number): Number of the page, which should be returned
    public page? : number = null;
    
    // Optional Argument for 'SearchSites' (number): Max count of Sites which should be returned
    public pageSize? : number = null;
    
  }
  
  /**
   * Contains results from calling 'SearchSites'.
   * Method: Loads Sites where values matching to the given filterExpression
   */
  export class SearchSitesResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string = null;
    
    // Return-Value of 'SearchSites' (Site[])
    public return : Site[];
    
  }
  
  /**
   * Contains arguments for calling 'AddNewSite'.
   * Method: Adds a new Site and returns its primary identifier (or null on failure).
   */
  export class AddNewSiteRequest {
    
    // Required Argument for 'AddNewSite' (Site): Site containing the new values
    public site : Site;
    
  }
  
  /**
   * Contains results from calling 'AddNewSite'.
   * Method: Adds a new Site and returns its primary identifier (or null on failure).
   */
  export class AddNewSiteResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string = null;
    
    // Return-Value of 'AddNewSite' (Boolean)
    public return : boolean;
    
  }
  
  /**
   * Contains arguments for calling 'UpdateSite'.
   * Method: Updates all values (which are not "FixedAfterCreation") of the given Site addressed by the primary identifier fields within the given Site. Returns false on failure or if no target record was found, otherwise true.
   */
  export class UpdateSiteRequest {
    
    // Required Argument for 'UpdateSite' (Site): Site containing the new values (the primary identifier fields within the given Site will be used to address the target record)
    public site : Site;
    
  }
  
  /**
   * Contains results from calling 'UpdateSite'.
   * Method: Updates all values (which are not "FixedAfterCreation") of the given Site addressed by the primary identifier fields within the given Site. Returns false on failure or if no target record was found, otherwise true.
   */
  export class UpdateSiteResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string = null;
    
    // Return-Value of 'UpdateSite' (Boolean)
    public return : boolean;
    
  }
  
  /**
   * Contains arguments for calling 'UpdateSiteBySiteUid'.
   * Method: Updates all values (which are not "FixedAfterCreation") of the given Site addressed by the supplementary given primary identifier. Returns false on failure or if no target record was found, otherwise true.
   */
  export class UpdateSiteBySiteUidRequest {
    
    // Required Argument for 'UpdateSiteBySiteUid' (string): An <see href="https://de.wikipedia.org/wiki/Universally_Unique_Identifier">Universally Unique Identifier</see> which can be generated by any origin system and is used to address this ORSCF conform data record in decentralized environments. Note that this Identity must not be changed any more!
    public siteUid : string;
    
    // Required Argument for 'UpdateSiteBySiteUid' (Site): Site containing the new values (the primary identifier fields within the given Site will be ignored)
    public site : Site;
    
  }
  
  /**
   * Contains results from calling 'UpdateSiteBySiteUid'.
   * Method: Updates all values (which are not "FixedAfterCreation") of the given Site addressed by the supplementary given primary identifier. Returns false on failure or if no target record was found, otherwise true.
   */
  export class UpdateSiteBySiteUidResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string = null;
    
    // Return-Value of 'UpdateSiteBySiteUid' (Boolean)
    public return : boolean;
    
  }
  
  /**
   * Contains arguments for calling 'DeleteSiteBySiteUid'.
   * Method: Deletes a specific Site addressed by the given primary identifier. Returns false on failure or if no target record was found, otherwise true.
   */
  export class DeleteSiteBySiteUidRequest {
    
    // Required Argument for 'DeleteSiteBySiteUid' (string): An <see href="https://de.wikipedia.org/wiki/Universally_Unique_Identifier">Universally Unique Identifier</see> which can be generated by any origin system and is used to address this ORSCF conform data record in decentralized environments. Note that this Identity must not be changed any more!
    public siteUid : string;
    
  }
  
  /**
   * Contains results from calling 'DeleteSiteBySiteUid'.
   * Method: Deletes a specific Site addressed by the given primary identifier. Returns false on failure or if no target record was found, otherwise true.
   */
  export class DeleteSiteBySiteUidResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string = null;
    
    // Return-Value of 'DeleteSiteBySiteUid' (Boolean)
    public return : boolean;
    
  }
  
  /**
   * Contains arguments for calling 'GetSystemEndpointBySystemEndpointUid'.
   * Method: Loads a specific SystemEndpoint addressed by the given primary identifier. Returns null on failure, or if no record exists with the given identity.
   */
  export class GetSystemEndpointBySystemEndpointUidRequest {
    
    // Required Argument for 'GetSystemEndpointBySystemEndpointUid' (string): Represents the primary identity of a SystemEndpoint
    public systemEndpointUid : string;
    
  }
  
  /**
   * Contains results from calling 'GetSystemEndpointBySystemEndpointUid'.
   * Method: Loads a specific SystemEndpoint addressed by the given primary identifier. Returns null on failure, or if no record exists with the given identity.
   */
  export class GetSystemEndpointBySystemEndpointUidResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string = null;
    
    // Return-Value of 'GetSystemEndpointBySystemEndpointUid' (SystemEndpoint)
    public return : SystemEndpoint;
    
  }
  
  /**
   * Contains arguments for calling 'GetSystemEndpoints'.
   * Method: Loads SystemEndpoints.
   */
  export class GetSystemEndpointsRequest {
    
    // Optional Argument for 'GetSystemEndpoints' (number): Number of the page, which should be returned
    public page? : number = null;
    
    // Optional Argument for 'GetSystemEndpoints' (number): Max count of SystemEndpoints which should be returned
    public pageSize? : number = null;
    
  }
  
  /**
   * Contains results from calling 'GetSystemEndpoints'.
   * Method: Loads SystemEndpoints.
   */
  export class GetSystemEndpointsResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string = null;
    
    // Return-Value of 'GetSystemEndpoints' (SystemEndpoint[])
    public return : SystemEndpoint[];
    
  }
  
  /**
   * Contains arguments for calling 'SearchSystemEndpoints'.
   * Method: Loads SystemEndpoints where values matching to the given filterExpression
   */
  export class SearchSystemEndpointsRequest {
    
    // Required Argument for 'SearchSystemEndpoints' (string): a filter expression like '((FieldName1 == "ABC" &amp;&amp; FieldName2 &gt; 12) || FieldName2 != "")'
    public filterExpression : string;
    
    // Optional Argument for 'SearchSystemEndpoints' (string): one or more property names which are used as sort order (before pagination)
    public sortingExpression? : string;
    
    // Optional Argument for 'SearchSystemEndpoints' (number): Number of the page, which should be returned
    public page? : number = null;
    
    // Optional Argument for 'SearchSystemEndpoints' (number): Max count of SystemEndpoints which should be returned
    public pageSize? : number = null;
    
  }
  
  /**
   * Contains results from calling 'SearchSystemEndpoints'.
   * Method: Loads SystemEndpoints where values matching to the given filterExpression
   */
  export class SearchSystemEndpointsResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string = null;
    
    // Return-Value of 'SearchSystemEndpoints' (SystemEndpoint[])
    public return : SystemEndpoint[];
    
  }
  
  /**
   * Contains arguments for calling 'AddNewSystemEndpoint'.
   * Method: Adds a new SystemEndpoint and returns its primary identifier (or null on failure).
   */
  export class AddNewSystemEndpointRequest {
    
    // Required Argument for 'AddNewSystemEndpoint' (SystemEndpoint): SystemEndpoint containing the new values
    public systemEndpoint : SystemEndpoint;
    
  }
  
  /**
   * Contains results from calling 'AddNewSystemEndpoint'.
   * Method: Adds a new SystemEndpoint and returns its primary identifier (or null on failure).
   */
  export class AddNewSystemEndpointResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string = null;
    
    // Return-Value of 'AddNewSystemEndpoint' (Boolean)
    public return : boolean;
    
  }
  
  /**
   * Contains arguments for calling 'UpdateSystemEndpoint'.
   * Method: Updates all values (which are not "FixedAfterCreation") of the given SystemEndpoint addressed by the primary identifier fields within the given SystemEndpoint. Returns false on failure or if no target record was found, otherwise true.
   */
  export class UpdateSystemEndpointRequest {
    
    // Required Argument for 'UpdateSystemEndpoint' (SystemEndpoint): SystemEndpoint containing the new values (the primary identifier fields within the given SystemEndpoint will be used to address the target record)
    public systemEndpoint : SystemEndpoint;
    
  }
  
  /**
   * Contains results from calling 'UpdateSystemEndpoint'.
   * Method: Updates all values (which are not "FixedAfterCreation") of the given SystemEndpoint addressed by the primary identifier fields within the given SystemEndpoint. Returns false on failure or if no target record was found, otherwise true.
   */
  export class UpdateSystemEndpointResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string = null;
    
    // Return-Value of 'UpdateSystemEndpoint' (Boolean)
    public return : boolean;
    
  }
  
  /**
   * Contains arguments for calling 'UpdateSystemEndpointBySystemEndpointUid'.
   * Method: Updates all values (which are not "FixedAfterCreation") of the given SystemEndpoint addressed by the supplementary given primary identifier. Returns false on failure or if no target record was found, otherwise true.
   */
  export class UpdateSystemEndpointBySystemEndpointUidRequest {
    
    // Required Argument for 'UpdateSystemEndpointBySystemEndpointUid' (string): Represents the primary identity of a SystemEndpoint
    public systemEndpointUid : string;
    
    // Required Argument for 'UpdateSystemEndpointBySystemEndpointUid' (SystemEndpoint): SystemEndpoint containing the new values (the primary identifier fields within the given SystemEndpoint will be ignored)
    public systemEndpoint : SystemEndpoint;
    
  }
  
  /**
   * Contains results from calling 'UpdateSystemEndpointBySystemEndpointUid'.
   * Method: Updates all values (which are not "FixedAfterCreation") of the given SystemEndpoint addressed by the supplementary given primary identifier. Returns false on failure or if no target record was found, otherwise true.
   */
  export class UpdateSystemEndpointBySystemEndpointUidResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string = null;
    
    // Return-Value of 'UpdateSystemEndpointBySystemEndpointUid' (Boolean)
    public return : boolean;
    
  }
  
  /**
   * Contains arguments for calling 'DeleteSystemEndpointBySystemEndpointUid'.
   * Method: Deletes a specific SystemEndpoint addressed by the given primary identifier. Returns false on failure or if no target record was found, otherwise true.
   */
  export class DeleteSystemEndpointBySystemEndpointUidRequest {
    
    // Required Argument for 'DeleteSystemEndpointBySystemEndpointUid' (string): Represents the primary identity of a SystemEndpoint
    public systemEndpointUid : string;
    
  }
  
  /**
   * Contains results from calling 'DeleteSystemEndpointBySystemEndpointUid'.
   * Method: Deletes a specific SystemEndpoint addressed by the given primary identifier. Returns false on failure or if no target record was found, otherwise true.
   */
  export class DeleteSystemEndpointBySystemEndpointUidResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string = null;
    
    // Return-Value of 'DeleteSystemEndpointBySystemEndpointUid' (Boolean)
    public return : boolean;
    
  }
  
  /**
   * Contains arguments for calling 'GetInstituteRelatedSystemAssignmentByInstituteRelatedSystemAssignemntUid'.
   * Method: Loads a specific InstituteRelatedSystemAssignment addressed by the given primary identifier. Returns null on failure, or if no record exists with the given identity.
   */
  export class GetInstituteRelatedSystemAssignmentByInstituteRelatedSystemAssignemntUidRequest {
    
    // Required Argument for 'GetInstituteRelatedSystemAssignmentByInstituteRelatedSystemAssignemntUid' (string): Represents the primary identity of a InstituteRelatedSystemAssignment
    public instituteRelatedSystemAssignemntUid : string;
    
  }
  
  /**
   * Contains results from calling 'GetInstituteRelatedSystemAssignmentByInstituteRelatedSystemAssignemntUid'.
   * Method: Loads a specific InstituteRelatedSystemAssignment addressed by the given primary identifier. Returns null on failure, or if no record exists with the given identity.
   */
  export class GetInstituteRelatedSystemAssignmentByInstituteRelatedSystemAssignemntUidResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string = null;
    
    // Return-Value of 'GetInstituteRelatedSystemAssignmentByInstituteRelatedSystemAssignemntUid' (InstituteRelatedSystemAssignment)
    public return : InstituteRelatedSystemAssignment;
    
  }
  
  /**
   * Contains arguments for calling 'GetInstituteRelatedSystemAssignments'.
   * Method: Loads InstituteRelatedSystemAssignments.
   */
  export class GetInstituteRelatedSystemAssignmentsRequest {
    
    // Optional Argument for 'GetInstituteRelatedSystemAssignments' (number): Number of the page, which should be returned
    public page? : number = null;
    
    // Optional Argument for 'GetInstituteRelatedSystemAssignments' (number): Max count of InstituteRelatedSystemAssignments which should be returned
    public pageSize? : number = null;
    
  }
  
  /**
   * Contains results from calling 'GetInstituteRelatedSystemAssignments'.
   * Method: Loads InstituteRelatedSystemAssignments.
   */
  export class GetInstituteRelatedSystemAssignmentsResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string = null;
    
    // Return-Value of 'GetInstituteRelatedSystemAssignments' (InstituteRelatedSystemAssignment[])
    public return : InstituteRelatedSystemAssignment[];
    
  }
  
  /**
   * Contains arguments for calling 'SearchInstituteRelatedSystemAssignments'.
   * Method: Loads InstituteRelatedSystemAssignments where values matching to the given filterExpression
   */
  export class SearchInstituteRelatedSystemAssignmentsRequest {
    
    // Required Argument for 'SearchInstituteRelatedSystemAssignments' (string): a filter expression like '((FieldName1 == "ABC" &amp;&amp; FieldName2 &gt; 12) || FieldName2 != "")'
    public filterExpression : string;
    
    // Optional Argument for 'SearchInstituteRelatedSystemAssignments' (string): one or more property names which are used as sort order (before pagination)
    public sortingExpression? : string;
    
    // Optional Argument for 'SearchInstituteRelatedSystemAssignments' (number): Number of the page, which should be returned
    public page? : number = null;
    
    // Optional Argument for 'SearchInstituteRelatedSystemAssignments' (number): Max count of InstituteRelatedSystemAssignments which should be returned
    public pageSize? : number = null;
    
  }
  
  /**
   * Contains results from calling 'SearchInstituteRelatedSystemAssignments'.
   * Method: Loads InstituteRelatedSystemAssignments where values matching to the given filterExpression
   */
  export class SearchInstituteRelatedSystemAssignmentsResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string = null;
    
    // Return-Value of 'SearchInstituteRelatedSystemAssignments' (InstituteRelatedSystemAssignment[])
    public return : InstituteRelatedSystemAssignment[];
    
  }
  
  /**
   * Contains arguments for calling 'AddNewInstituteRelatedSystemAssignment'.
   * Method: Adds a new InstituteRelatedSystemAssignment and returns its primary identifier (or null on failure).
   */
  export class AddNewInstituteRelatedSystemAssignmentRequest {
    
    // Required Argument for 'AddNewInstituteRelatedSystemAssignment' (InstituteRelatedSystemAssignment): InstituteRelatedSystemAssignment containing the new values
    public instituteRelatedSystemAssignment : InstituteRelatedSystemAssignment;
    
  }
  
  /**
   * Contains results from calling 'AddNewInstituteRelatedSystemAssignment'.
   * Method: Adds a new InstituteRelatedSystemAssignment and returns its primary identifier (or null on failure).
   */
  export class AddNewInstituteRelatedSystemAssignmentResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string = null;
    
    // Return-Value of 'AddNewInstituteRelatedSystemAssignment' (Boolean)
    public return : boolean;
    
  }
  
  /**
   * Contains arguments for calling 'UpdateInstituteRelatedSystemAssignment'.
   * Method: Updates all values (which are not "FixedAfterCreation") of the given InstituteRelatedSystemAssignment addressed by the primary identifier fields within the given InstituteRelatedSystemAssignment. Returns false on failure or if no target record was found, otherwise true.
   */
  export class UpdateInstituteRelatedSystemAssignmentRequest {
    
    // Required Argument for 'UpdateInstituteRelatedSystemAssignment' (InstituteRelatedSystemAssignment): InstituteRelatedSystemAssignment containing the new values (the primary identifier fields within the given InstituteRelatedSystemAssignment will be used to address the target record)
    public instituteRelatedSystemAssignment : InstituteRelatedSystemAssignment;
    
  }
  
  /**
   * Contains results from calling 'UpdateInstituteRelatedSystemAssignment'.
   * Method: Updates all values (which are not "FixedAfterCreation") of the given InstituteRelatedSystemAssignment addressed by the primary identifier fields within the given InstituteRelatedSystemAssignment. Returns false on failure or if no target record was found, otherwise true.
   */
  export class UpdateInstituteRelatedSystemAssignmentResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string = null;
    
    // Return-Value of 'UpdateInstituteRelatedSystemAssignment' (Boolean)
    public return : boolean;
    
  }
  
  /**
   * Contains arguments for calling 'UpdateInstituteRelatedSystemAssignmentByInstituteRelatedSystemAssignemntUid'.
   * Method: Updates all values (which are not "FixedAfterCreation") of the given InstituteRelatedSystemAssignment addressed by the supplementary given primary identifier. Returns false on failure or if no target record was found, otherwise true.
   */
  export class UpdateInstituteRelatedSystemAssignmentByInstituteRelatedSystemAssignemntUidRequest {
    
    // Required Argument for 'UpdateInstituteRelatedSystemAssignmentByInstituteRelatedSystemAssignemntUid' (string): Represents the primary identity of a InstituteRelatedSystemAssignment
    public instituteRelatedSystemAssignemntUid : string;
    
    // Required Argument for 'UpdateInstituteRelatedSystemAssignmentByInstituteRelatedSystemAssignemntUid' (InstituteRelatedSystemAssignment): InstituteRelatedSystemAssignment containing the new values (the primary identifier fields within the given InstituteRelatedSystemAssignment will be ignored)
    public instituteRelatedSystemAssignment : InstituteRelatedSystemAssignment;
    
  }
  
  /**
   * Contains results from calling 'UpdateInstituteRelatedSystemAssignmentByInstituteRelatedSystemAssignemntUid'.
   * Method: Updates all values (which are not "FixedAfterCreation") of the given InstituteRelatedSystemAssignment addressed by the supplementary given primary identifier. Returns false on failure or if no target record was found, otherwise true.
   */
  export class UpdateInstituteRelatedSystemAssignmentByInstituteRelatedSystemAssignemntUidResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string = null;
    
    // Return-Value of 'UpdateInstituteRelatedSystemAssignmentByInstituteRelatedSystemAssignemntUid' (Boolean)
    public return : boolean;
    
  }
  
  /**
   * Contains arguments for calling 'DeleteInstituteRelatedSystemAssignmentByInstituteRelatedSystemAssignemntUid'.
   * Method: Deletes a specific InstituteRelatedSystemAssignment addressed by the given primary identifier. Returns false on failure or if no target record was found, otherwise true.
   */
  export class DeleteInstituteRelatedSystemAssignmentByInstituteRelatedSystemAssignemntUidRequest {
    
    // Required Argument for 'DeleteInstituteRelatedSystemAssignmentByInstituteRelatedSystemAssignemntUid' (string): Represents the primary identity of a InstituteRelatedSystemAssignment
    public instituteRelatedSystemAssignemntUid : string;
    
  }
  
  /**
   * Contains results from calling 'DeleteInstituteRelatedSystemAssignmentByInstituteRelatedSystemAssignemntUid'.
   * Method: Deletes a specific InstituteRelatedSystemAssignment addressed by the given primary identifier. Returns false on failure or if no target record was found, otherwise true.
   */
  export class DeleteInstituteRelatedSystemAssignmentByInstituteRelatedSystemAssignemntUidResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string = null;
    
    // Return-Value of 'DeleteInstituteRelatedSystemAssignmentByInstituteRelatedSystemAssignemntUid' (Boolean)
    public return : boolean;
    
  }
  
  /**
   * Contains arguments for calling 'GetSystemConnectionBySystemConnectionUid'.
   * Method: Loads a specific SystemConnection addressed by the given primary identifier. Returns null on failure, or if no record exists with the given identity.
   */
  export class GetSystemConnectionBySystemConnectionUidRequest {
    
    // Required Argument for 'GetSystemConnectionBySystemConnectionUid' (string): Represents the primary identity of a SystemConnection
    public systemConnectionUid : string;
    
  }
  
  /**
   * Contains results from calling 'GetSystemConnectionBySystemConnectionUid'.
   * Method: Loads a specific SystemConnection addressed by the given primary identifier. Returns null on failure, or if no record exists with the given identity.
   */
  export class GetSystemConnectionBySystemConnectionUidResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string = null;
    
    // Return-Value of 'GetSystemConnectionBySystemConnectionUid' (SystemConnection)
    public return : SystemConnection;
    
  }
  
  /**
   * Contains arguments for calling 'GetSystemConnections'.
   * Method: Loads SystemConnections.
   */
  export class GetSystemConnectionsRequest {
    
    // Optional Argument for 'GetSystemConnections' (number): Number of the page, which should be returned
    public page? : number = null;
    
    // Optional Argument for 'GetSystemConnections' (number): Max count of SystemConnections which should be returned
    public pageSize? : number = null;
    
  }
  
  /**
   * Contains results from calling 'GetSystemConnections'.
   * Method: Loads SystemConnections.
   */
  export class GetSystemConnectionsResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string = null;
    
    // Return-Value of 'GetSystemConnections' (SystemConnection[])
    public return : SystemConnection[];
    
  }
  
  /**
   * Contains arguments for calling 'SearchSystemConnections'.
   * Method: Loads SystemConnections where values matching to the given filterExpression
   */
  export class SearchSystemConnectionsRequest {
    
    // Required Argument for 'SearchSystemConnections' (string): a filter expression like '((FieldName1 == "ABC" &amp;&amp; FieldName2 &gt; 12) || FieldName2 != "")'
    public filterExpression : string;
    
    // Optional Argument for 'SearchSystemConnections' (string): one or more property names which are used as sort order (before pagination)
    public sortingExpression? : string;
    
    // Optional Argument for 'SearchSystemConnections' (number): Number of the page, which should be returned
    public page? : number = null;
    
    // Optional Argument for 'SearchSystemConnections' (number): Max count of SystemConnections which should be returned
    public pageSize? : number = null;
    
  }
  
  /**
   * Contains results from calling 'SearchSystemConnections'.
   * Method: Loads SystemConnections where values matching to the given filterExpression
   */
  export class SearchSystemConnectionsResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string = null;
    
    // Return-Value of 'SearchSystemConnections' (SystemConnection[])
    public return : SystemConnection[];
    
  }
  
  /**
   * Contains arguments for calling 'AddNewSystemConnection'.
   * Method: Adds a new SystemConnection and returns its primary identifier (or null on failure).
   */
  export class AddNewSystemConnectionRequest {
    
    // Required Argument for 'AddNewSystemConnection' (SystemConnection): SystemConnection containing the new values
    public systemConnection : SystemConnection;
    
  }
  
  /**
   * Contains results from calling 'AddNewSystemConnection'.
   * Method: Adds a new SystemConnection and returns its primary identifier (or null on failure).
   */
  export class AddNewSystemConnectionResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string = null;
    
    // Return-Value of 'AddNewSystemConnection' (Boolean)
    public return : boolean;
    
  }
  
  /**
   * Contains arguments for calling 'UpdateSystemConnection'.
   * Method: Updates all values (which are not "FixedAfterCreation") of the given SystemConnection addressed by the primary identifier fields within the given SystemConnection. Returns false on failure or if no target record was found, otherwise true.
   */
  export class UpdateSystemConnectionRequest {
    
    // Required Argument for 'UpdateSystemConnection' (SystemConnection): SystemConnection containing the new values (the primary identifier fields within the given SystemConnection will be used to address the target record)
    public systemConnection : SystemConnection;
    
  }
  
  /**
   * Contains results from calling 'UpdateSystemConnection'.
   * Method: Updates all values (which are not "FixedAfterCreation") of the given SystemConnection addressed by the primary identifier fields within the given SystemConnection. Returns false on failure or if no target record was found, otherwise true.
   */
  export class UpdateSystemConnectionResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string = null;
    
    // Return-Value of 'UpdateSystemConnection' (Boolean)
    public return : boolean;
    
  }
  
  /**
   * Contains arguments for calling 'UpdateSystemConnectionBySystemConnectionUid'.
   * Method: Updates all values (which are not "FixedAfterCreation") of the given SystemConnection addressed by the supplementary given primary identifier. Returns false on failure or if no target record was found, otherwise true.
   */
  export class UpdateSystemConnectionBySystemConnectionUidRequest {
    
    // Required Argument for 'UpdateSystemConnectionBySystemConnectionUid' (string): Represents the primary identity of a SystemConnection
    public systemConnectionUid : string;
    
    // Required Argument for 'UpdateSystemConnectionBySystemConnectionUid' (SystemConnection): SystemConnection containing the new values (the primary identifier fields within the given SystemConnection will be ignored)
    public systemConnection : SystemConnection;
    
  }
  
  /**
   * Contains results from calling 'UpdateSystemConnectionBySystemConnectionUid'.
   * Method: Updates all values (which are not "FixedAfterCreation") of the given SystemConnection addressed by the supplementary given primary identifier. Returns false on failure or if no target record was found, otherwise true.
   */
  export class UpdateSystemConnectionBySystemConnectionUidResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string = null;
    
    // Return-Value of 'UpdateSystemConnectionBySystemConnectionUid' (Boolean)
    public return : boolean;
    
  }
  
  /**
   * Contains arguments for calling 'DeleteSystemConnectionBySystemConnectionUid'.
   * Method: Deletes a specific SystemConnection addressed by the given primary identifier. Returns false on failure or if no target record was found, otherwise true.
   */
  export class DeleteSystemConnectionBySystemConnectionUidRequest {
    
    // Required Argument for 'DeleteSystemConnectionBySystemConnectionUid' (string): Represents the primary identity of a SystemConnection
    public systemConnectionUid : string;
    
  }
  
  /**
   * Contains results from calling 'DeleteSystemConnectionBySystemConnectionUid'.
   * Method: Deletes a specific SystemConnection addressed by the given primary identifier. Returns false on failure or if no target record was found, otherwise true.
   */
  export class DeleteSystemConnectionBySystemConnectionUidResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string = null;
    
    // Return-Value of 'DeleteSystemConnectionBySystemConnectionUid' (Boolean)
    public return : boolean;
    
  }
  
  /**
   * Contains arguments for calling 'GetInvolvedPersonByInvolvedPersonUid'.
   * Method: Loads a specific InvolvedPerson addressed by the given primary identifier. Returns null on failure, or if no record exists with the given identity.
   */
  export class GetInvolvedPersonByInvolvedPersonUidRequest {
    
    // Required Argument for 'GetInvolvedPersonByInvolvedPersonUid' (string): An <see href="https://de.wikipedia.org/wiki/Universally_Unique_Identifier">Universally Unique Identifier</see> which can be generated by any origin system and is used to address this ORSCF conform data record in decentralized environments. Note that this Identity must not be changed any more!
    public involvedPersonUid : string;
    
  }
  
  /**
   * Contains results from calling 'GetInvolvedPersonByInvolvedPersonUid'.
   * Method: Loads a specific InvolvedPerson addressed by the given primary identifier. Returns null on failure, or if no record exists with the given identity.
   */
  export class GetInvolvedPersonByInvolvedPersonUidResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string = null;
    
    // Return-Value of 'GetInvolvedPersonByInvolvedPersonUid' (InvolvedPerson)
    public return : InvolvedPerson;
    
  }
  
  /**
   * Contains arguments for calling 'GetInvolvedPersons'.
   * Method: Loads InvolvedPersons.
   */
  export class GetInvolvedPersonsRequest {
    
    // Optional Argument for 'GetInvolvedPersons' (number): Number of the page, which should be returned
    public page? : number = null;
    
    // Optional Argument for 'GetInvolvedPersons' (number): Max count of InvolvedPersons which should be returned
    public pageSize? : number = null;
    
  }
  
  /**
   * Contains results from calling 'GetInvolvedPersons'.
   * Method: Loads InvolvedPersons.
   */
  export class GetInvolvedPersonsResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string = null;
    
    // Return-Value of 'GetInvolvedPersons' (InvolvedPerson[])
    public return : InvolvedPerson[];
    
  }
  
  /**
   * Contains arguments for calling 'SearchInvolvedPersons'.
   * Method: Loads InvolvedPersons where values matching to the given filterExpression
   */
  export class SearchInvolvedPersonsRequest {
    
    // Required Argument for 'SearchInvolvedPersons' (string): a filter expression like '((FieldName1 == "ABC" &amp;&amp; FieldName2 &gt; 12) || FieldName2 != "")'
    public filterExpression : string;
    
    // Optional Argument for 'SearchInvolvedPersons' (string): one or more property names which are used as sort order (before pagination)
    public sortingExpression? : string;
    
    // Optional Argument for 'SearchInvolvedPersons' (number): Number of the page, which should be returned
    public page? : number = null;
    
    // Optional Argument for 'SearchInvolvedPersons' (number): Max count of InvolvedPersons which should be returned
    public pageSize? : number = null;
    
  }
  
  /**
   * Contains results from calling 'SearchInvolvedPersons'.
   * Method: Loads InvolvedPersons where values matching to the given filterExpression
   */
  export class SearchInvolvedPersonsResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string = null;
    
    // Return-Value of 'SearchInvolvedPersons' (InvolvedPerson[])
    public return : InvolvedPerson[];
    
  }
  
  /**
   * Contains arguments for calling 'AddNewInvolvedPerson'.
   * Method: Adds a new InvolvedPerson and returns its primary identifier (or null on failure).
   */
  export class AddNewInvolvedPersonRequest {
    
    // Required Argument for 'AddNewInvolvedPerson' (InvolvedPerson): InvolvedPerson containing the new values
    public involvedPerson : InvolvedPerson;
    
  }
  
  /**
   * Contains results from calling 'AddNewInvolvedPerson'.
   * Method: Adds a new InvolvedPerson and returns its primary identifier (or null on failure).
   */
  export class AddNewInvolvedPersonResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string = null;
    
    // Return-Value of 'AddNewInvolvedPerson' (Boolean)
    public return : boolean;
    
  }
  
  /**
   * Contains arguments for calling 'UpdateInvolvedPerson'.
   * Method: Updates all values (which are not "FixedAfterCreation") of the given InvolvedPerson addressed by the primary identifier fields within the given InvolvedPerson. Returns false on failure or if no target record was found, otherwise true.
   */
  export class UpdateInvolvedPersonRequest {
    
    // Required Argument for 'UpdateInvolvedPerson' (InvolvedPerson): InvolvedPerson containing the new values (the primary identifier fields within the given InvolvedPerson will be used to address the target record)
    public involvedPerson : InvolvedPerson;
    
  }
  
  /**
   * Contains results from calling 'UpdateInvolvedPerson'.
   * Method: Updates all values (which are not "FixedAfterCreation") of the given InvolvedPerson addressed by the primary identifier fields within the given InvolvedPerson. Returns false on failure or if no target record was found, otherwise true.
   */
  export class UpdateInvolvedPersonResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string = null;
    
    // Return-Value of 'UpdateInvolvedPerson' (Boolean)
    public return : boolean;
    
  }
  
  /**
   * Contains arguments for calling 'UpdateInvolvedPersonByInvolvedPersonUid'.
   * Method: Updates all values (which are not "FixedAfterCreation") of the given InvolvedPerson addressed by the supplementary given primary identifier. Returns false on failure or if no target record was found, otherwise true.
   */
  export class UpdateInvolvedPersonByInvolvedPersonUidRequest {
    
    // Required Argument for 'UpdateInvolvedPersonByInvolvedPersonUid' (string): An <see href="https://de.wikipedia.org/wiki/Universally_Unique_Identifier">Universally Unique Identifier</see> which can be generated by any origin system and is used to address this ORSCF conform data record in decentralized environments. Note that this Identity must not be changed any more!
    public involvedPersonUid : string;
    
    // Required Argument for 'UpdateInvolvedPersonByInvolvedPersonUid' (InvolvedPerson): InvolvedPerson containing the new values (the primary identifier fields within the given InvolvedPerson will be ignored)
    public involvedPerson : InvolvedPerson;
    
  }
  
  /**
   * Contains results from calling 'UpdateInvolvedPersonByInvolvedPersonUid'.
   * Method: Updates all values (which are not "FixedAfterCreation") of the given InvolvedPerson addressed by the supplementary given primary identifier. Returns false on failure or if no target record was found, otherwise true.
   */
  export class UpdateInvolvedPersonByInvolvedPersonUidResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string = null;
    
    // Return-Value of 'UpdateInvolvedPersonByInvolvedPersonUid' (Boolean)
    public return : boolean;
    
  }
  
  /**
   * Contains arguments for calling 'DeleteInvolvedPersonByInvolvedPersonUid'.
   * Method: Deletes a specific InvolvedPerson addressed by the given primary identifier. Returns false on failure or if no target record was found, otherwise true.
   */
  export class DeleteInvolvedPersonByInvolvedPersonUidRequest {
    
    // Required Argument for 'DeleteInvolvedPersonByInvolvedPersonUid' (string): An <see href="https://de.wikipedia.org/wiki/Universally_Unique_Identifier">Universally Unique Identifier</see> which can be generated by any origin system and is used to address this ORSCF conform data record in decentralized environments. Note that this Identity must not be changed any more!
    public involvedPersonUid : string;
    
  }
  
  /**
   * Contains results from calling 'DeleteInvolvedPersonByInvolvedPersonUid'.
   * Method: Deletes a specific InvolvedPerson addressed by the given primary identifier. Returns false on failure or if no target record was found, otherwise true.
   */
  export class DeleteInvolvedPersonByInvolvedPersonUidResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string = null;
    
    // Return-Value of 'DeleteInvolvedPersonByInvolvedPersonUid' (Boolean)
    public return : boolean;
    
  }
  
  /**
   * Contains arguments for calling 'GetInvolvementRoleByInvolvedPersonRoleUid'.
   * Method: Loads a specific InvolvementRole addressed by the given primary identifier. Returns null on failure, or if no record exists with the given identity.
   */
  export class GetInvolvementRoleByInvolvedPersonRoleUidRequest {
    
    // Required Argument for 'GetInvolvementRoleByInvolvedPersonRoleUid' (string): An <see href="https://de.wikipedia.org/wiki/Universally_Unique_Identifier">Universally Unique Identifier</see> which can be generated by any origin system and is used to address this ORSCF conform data record in decentralized environments. Note that this Identity must not be changed any more!
    public involvedPersonRoleUid : string;
    
  }
  
  /**
   * Contains results from calling 'GetInvolvementRoleByInvolvedPersonRoleUid'.
   * Method: Loads a specific InvolvementRole addressed by the given primary identifier. Returns null on failure, or if no record exists with the given identity.
   */
  export class GetInvolvementRoleByInvolvedPersonRoleUidResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string = null;
    
    // Return-Value of 'GetInvolvementRoleByInvolvedPersonRoleUid' (InvolvementRole)
    public return : InvolvementRole;
    
  }
  
  /**
   * Contains arguments for calling 'GetInvolvementRoles'.
   * Method: Loads InvolvementRoles.
   */
  export class GetInvolvementRolesRequest {
    
    // Optional Argument for 'GetInvolvementRoles' (number): Number of the page, which should be returned
    public page? : number = null;
    
    // Optional Argument for 'GetInvolvementRoles' (number): Max count of InvolvementRoles which should be returned
    public pageSize? : number = null;
    
  }
  
  /**
   * Contains results from calling 'GetInvolvementRoles'.
   * Method: Loads InvolvementRoles.
   */
  export class GetInvolvementRolesResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string = null;
    
    // Return-Value of 'GetInvolvementRoles' (InvolvementRole[])
    public return : InvolvementRole[];
    
  }
  
  /**
   * Contains arguments for calling 'SearchInvolvementRoles'.
   * Method: Loads InvolvementRoles where values matching to the given filterExpression
   */
  export class SearchInvolvementRolesRequest {
    
    // Required Argument for 'SearchInvolvementRoles' (string): a filter expression like '((FieldName1 == "ABC" &amp;&amp; FieldName2 &gt; 12) || FieldName2 != "")'
    public filterExpression : string;
    
    // Optional Argument for 'SearchInvolvementRoles' (string): one or more property names which are used as sort order (before pagination)
    public sortingExpression? : string;
    
    // Optional Argument for 'SearchInvolvementRoles' (number): Number of the page, which should be returned
    public page? : number = null;
    
    // Optional Argument for 'SearchInvolvementRoles' (number): Max count of InvolvementRoles which should be returned
    public pageSize? : number = null;
    
  }
  
  /**
   * Contains results from calling 'SearchInvolvementRoles'.
   * Method: Loads InvolvementRoles where values matching to the given filterExpression
   */
  export class SearchInvolvementRolesResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string = null;
    
    // Return-Value of 'SearchInvolvementRoles' (InvolvementRole[])
    public return : InvolvementRole[];
    
  }
  
  /**
   * Contains arguments for calling 'AddNewInvolvementRole'.
   * Method: Adds a new InvolvementRole and returns its primary identifier (or null on failure).
   */
  export class AddNewInvolvementRoleRequest {
    
    // Required Argument for 'AddNewInvolvementRole' (InvolvementRole): InvolvementRole containing the new values
    public involvementRole : InvolvementRole;
    
  }
  
  /**
   * Contains results from calling 'AddNewInvolvementRole'.
   * Method: Adds a new InvolvementRole and returns its primary identifier (or null on failure).
   */
  export class AddNewInvolvementRoleResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string = null;
    
    // Return-Value of 'AddNewInvolvementRole' (Boolean)
    public return : boolean;
    
  }
  
  /**
   * Contains arguments for calling 'UpdateInvolvementRole'.
   * Method: Updates all values (which are not "FixedAfterCreation") of the given InvolvementRole addressed by the primary identifier fields within the given InvolvementRole. Returns false on failure or if no target record was found, otherwise true.
   */
  export class UpdateInvolvementRoleRequest {
    
    // Required Argument for 'UpdateInvolvementRole' (InvolvementRole): InvolvementRole containing the new values (the primary identifier fields within the given InvolvementRole will be used to address the target record)
    public involvementRole : InvolvementRole;
    
  }
  
  /**
   * Contains results from calling 'UpdateInvolvementRole'.
   * Method: Updates all values (which are not "FixedAfterCreation") of the given InvolvementRole addressed by the primary identifier fields within the given InvolvementRole. Returns false on failure or if no target record was found, otherwise true.
   */
  export class UpdateInvolvementRoleResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string = null;
    
    // Return-Value of 'UpdateInvolvementRole' (Boolean)
    public return : boolean;
    
  }
  
  /**
   * Contains arguments for calling 'UpdateInvolvementRoleByInvolvedPersonRoleUid'.
   * Method: Updates all values (which are not "FixedAfterCreation") of the given InvolvementRole addressed by the supplementary given primary identifier. Returns false on failure or if no target record was found, otherwise true.
   */
  export class UpdateInvolvementRoleByInvolvedPersonRoleUidRequest {
    
    // Required Argument for 'UpdateInvolvementRoleByInvolvedPersonRoleUid' (string): An <see href="https://de.wikipedia.org/wiki/Universally_Unique_Identifier">Universally Unique Identifier</see> which can be generated by any origin system and is used to address this ORSCF conform data record in decentralized environments. Note that this Identity must not be changed any more!
    public involvedPersonRoleUid : string;
    
    // Required Argument for 'UpdateInvolvementRoleByInvolvedPersonRoleUid' (InvolvementRole): InvolvementRole containing the new values (the primary identifier fields within the given InvolvementRole will be ignored)
    public involvementRole : InvolvementRole;
    
  }
  
  /**
   * Contains results from calling 'UpdateInvolvementRoleByInvolvedPersonRoleUid'.
   * Method: Updates all values (which are not "FixedAfterCreation") of the given InvolvementRole addressed by the supplementary given primary identifier. Returns false on failure or if no target record was found, otherwise true.
   */
  export class UpdateInvolvementRoleByInvolvedPersonRoleUidResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string = null;
    
    // Return-Value of 'UpdateInvolvementRoleByInvolvedPersonRoleUid' (Boolean)
    public return : boolean;
    
  }
  
  /**
   * Contains arguments for calling 'DeleteInvolvementRoleByInvolvedPersonRoleUid'.
   * Method: Deletes a specific InvolvementRole addressed by the given primary identifier. Returns false on failure or if no target record was found, otherwise true.
   */
  export class DeleteInvolvementRoleByInvolvedPersonRoleUidRequest {
    
    // Required Argument for 'DeleteInvolvementRoleByInvolvedPersonRoleUid' (string): An <see href="https://de.wikipedia.org/wiki/Universally_Unique_Identifier">Universally Unique Identifier</see> which can be generated by any origin system and is used to address this ORSCF conform data record in decentralized environments. Note that this Identity must not be changed any more!
    public involvedPersonRoleUid : string;
    
  }
  
  /**
   * Contains results from calling 'DeleteInvolvementRoleByInvolvedPersonRoleUid'.
   * Method: Deletes a specific InvolvementRole addressed by the given primary identifier. Returns false on failure or if no target record was found, otherwise true.
   */
  export class DeleteInvolvementRoleByInvolvedPersonRoleUidResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string = null;
    
    // Return-Value of 'DeleteInvolvementRoleByInvolvedPersonRoleUid' (Boolean)
    public return : boolean;
    
  }
  
  /**
   * Contains arguments for calling 'GetStudyRelatedSystemAssignmentByStudyRelatedSystemAssignmentUid'.
   * Method: Loads a specific StudyRelatedSystemAssignment addressed by the given primary identifier. Returns null on failure, or if no record exists with the given identity.
   */
  export class GetStudyRelatedSystemAssignmentByStudyRelatedSystemAssignmentUidRequest {
    
    // Required Argument for 'GetStudyRelatedSystemAssignmentByStudyRelatedSystemAssignmentUid' (string): Represents the primary identity of a StudyRelatedSystemAssignment
    public studyRelatedSystemAssignmentUid : string;
    
  }
  
  /**
   * Contains results from calling 'GetStudyRelatedSystemAssignmentByStudyRelatedSystemAssignmentUid'.
   * Method: Loads a specific StudyRelatedSystemAssignment addressed by the given primary identifier. Returns null on failure, or if no record exists with the given identity.
   */
  export class GetStudyRelatedSystemAssignmentByStudyRelatedSystemAssignmentUidResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string = null;
    
    // Return-Value of 'GetStudyRelatedSystemAssignmentByStudyRelatedSystemAssignmentUid' (StudyRelatedSystemAssignment)
    public return : StudyRelatedSystemAssignment;
    
  }
  
  /**
   * Contains arguments for calling 'GetStudyRelatedSystemAssignments'.
   * Method: Loads StudyRelatedSystemAssignments.
   */
  export class GetStudyRelatedSystemAssignmentsRequest {
    
    // Optional Argument for 'GetStudyRelatedSystemAssignments' (number): Number of the page, which should be returned
    public page? : number = null;
    
    // Optional Argument for 'GetStudyRelatedSystemAssignments' (number): Max count of StudyRelatedSystemAssignments which should be returned
    public pageSize? : number = null;
    
  }
  
  /**
   * Contains results from calling 'GetStudyRelatedSystemAssignments'.
   * Method: Loads StudyRelatedSystemAssignments.
   */
  export class GetStudyRelatedSystemAssignmentsResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string = null;
    
    // Return-Value of 'GetStudyRelatedSystemAssignments' (StudyRelatedSystemAssignment[])
    public return : StudyRelatedSystemAssignment[];
    
  }
  
  /**
   * Contains arguments for calling 'SearchStudyRelatedSystemAssignments'.
   * Method: Loads StudyRelatedSystemAssignments where values matching to the given filterExpression
   */
  export class SearchStudyRelatedSystemAssignmentsRequest {
    
    // Required Argument for 'SearchStudyRelatedSystemAssignments' (string): a filter expression like '((FieldName1 == "ABC" &amp;&amp; FieldName2 &gt; 12) || FieldName2 != "")'
    public filterExpression : string;
    
    // Optional Argument for 'SearchStudyRelatedSystemAssignments' (string): one or more property names which are used as sort order (before pagination)
    public sortingExpression? : string;
    
    // Optional Argument for 'SearchStudyRelatedSystemAssignments' (number): Number of the page, which should be returned
    public page? : number = null;
    
    // Optional Argument for 'SearchStudyRelatedSystemAssignments' (number): Max count of StudyRelatedSystemAssignments which should be returned
    public pageSize? : number = null;
    
  }
  
  /**
   * Contains results from calling 'SearchStudyRelatedSystemAssignments'.
   * Method: Loads StudyRelatedSystemAssignments where values matching to the given filterExpression
   */
  export class SearchStudyRelatedSystemAssignmentsResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string = null;
    
    // Return-Value of 'SearchStudyRelatedSystemAssignments' (StudyRelatedSystemAssignment[])
    public return : StudyRelatedSystemAssignment[];
    
  }
  
  /**
   * Contains arguments for calling 'AddNewStudyRelatedSystemAssignment'.
   * Method: Adds a new StudyRelatedSystemAssignment and returns its primary identifier (or null on failure).
   */
  export class AddNewStudyRelatedSystemAssignmentRequest {
    
    // Required Argument for 'AddNewStudyRelatedSystemAssignment' (StudyRelatedSystemAssignment): StudyRelatedSystemAssignment containing the new values
    public studyRelatedSystemAssignment : StudyRelatedSystemAssignment;
    
  }
  
  /**
   * Contains results from calling 'AddNewStudyRelatedSystemAssignment'.
   * Method: Adds a new StudyRelatedSystemAssignment and returns its primary identifier (or null on failure).
   */
  export class AddNewStudyRelatedSystemAssignmentResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string = null;
    
    // Return-Value of 'AddNewStudyRelatedSystemAssignment' (Boolean)
    public return : boolean;
    
  }
  
  /**
   * Contains arguments for calling 'UpdateStudyRelatedSystemAssignment'.
   * Method: Updates all values (which are not "FixedAfterCreation") of the given StudyRelatedSystemAssignment addressed by the primary identifier fields within the given StudyRelatedSystemAssignment. Returns false on failure or if no target record was found, otherwise true.
   */
  export class UpdateStudyRelatedSystemAssignmentRequest {
    
    // Required Argument for 'UpdateStudyRelatedSystemAssignment' (StudyRelatedSystemAssignment): StudyRelatedSystemAssignment containing the new values (the primary identifier fields within the given StudyRelatedSystemAssignment will be used to address the target record)
    public studyRelatedSystemAssignment : StudyRelatedSystemAssignment;
    
  }
  
  /**
   * Contains results from calling 'UpdateStudyRelatedSystemAssignment'.
   * Method: Updates all values (which are not "FixedAfterCreation") of the given StudyRelatedSystemAssignment addressed by the primary identifier fields within the given StudyRelatedSystemAssignment. Returns false on failure or if no target record was found, otherwise true.
   */
  export class UpdateStudyRelatedSystemAssignmentResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string = null;
    
    // Return-Value of 'UpdateStudyRelatedSystemAssignment' (Boolean)
    public return : boolean;
    
  }
  
  /**
   * Contains arguments for calling 'UpdateStudyRelatedSystemAssignmentByStudyRelatedSystemAssignmentUid'.
   * Method: Updates all values (which are not "FixedAfterCreation") of the given StudyRelatedSystemAssignment addressed by the supplementary given primary identifier. Returns false on failure or if no target record was found, otherwise true.
   */
  export class UpdateStudyRelatedSystemAssignmentByStudyRelatedSystemAssignmentUidRequest {
    
    // Required Argument for 'UpdateStudyRelatedSystemAssignmentByStudyRelatedSystemAssignmentUid' (string): Represents the primary identity of a StudyRelatedSystemAssignment
    public studyRelatedSystemAssignmentUid : string;
    
    // Required Argument for 'UpdateStudyRelatedSystemAssignmentByStudyRelatedSystemAssignmentUid' (StudyRelatedSystemAssignment): StudyRelatedSystemAssignment containing the new values (the primary identifier fields within the given StudyRelatedSystemAssignment will be ignored)
    public studyRelatedSystemAssignment : StudyRelatedSystemAssignment;
    
  }
  
  /**
   * Contains results from calling 'UpdateStudyRelatedSystemAssignmentByStudyRelatedSystemAssignmentUid'.
   * Method: Updates all values (which are not "FixedAfterCreation") of the given StudyRelatedSystemAssignment addressed by the supplementary given primary identifier. Returns false on failure or if no target record was found, otherwise true.
   */
  export class UpdateStudyRelatedSystemAssignmentByStudyRelatedSystemAssignmentUidResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string = null;
    
    // Return-Value of 'UpdateStudyRelatedSystemAssignmentByStudyRelatedSystemAssignmentUid' (Boolean)
    public return : boolean;
    
  }
  
  /**
   * Contains arguments for calling 'DeleteStudyRelatedSystemAssignmentByStudyRelatedSystemAssignmentUid'.
   * Method: Deletes a specific StudyRelatedSystemAssignment addressed by the given primary identifier. Returns false on failure or if no target record was found, otherwise true.
   */
  export class DeleteStudyRelatedSystemAssignmentByStudyRelatedSystemAssignmentUidRequest {
    
    // Required Argument for 'DeleteStudyRelatedSystemAssignmentByStudyRelatedSystemAssignmentUid' (string): Represents the primary identity of a StudyRelatedSystemAssignment
    public studyRelatedSystemAssignmentUid : string;
    
  }
  
  /**
   * Contains results from calling 'DeleteStudyRelatedSystemAssignmentByStudyRelatedSystemAssignmentUid'.
   * Method: Deletes a specific StudyRelatedSystemAssignment addressed by the given primary identifier. Returns false on failure or if no target record was found, otherwise true.
   */
  export class DeleteStudyRelatedSystemAssignmentByStudyRelatedSystemAssignmentUidResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string = null;
    
    // Return-Value of 'DeleteStudyRelatedSystemAssignmentByStudyRelatedSystemAssignmentUid' (Boolean)
    public return : boolean;
    
  }
  
  /**
   * Contains arguments for calling 'GetSiteRelatedSystemAssignmentBySiteRelatedSystemAssignmentUid'.
   * Method: Loads a specific SiteRelatedSystemAssignment addressed by the given primary identifier. Returns null on failure, or if no record exists with the given identity.
   */
  export class GetSiteRelatedSystemAssignmentBySiteRelatedSystemAssignmentUidRequest {
    
    // Required Argument for 'GetSiteRelatedSystemAssignmentBySiteRelatedSystemAssignmentUid' (string): Represents the primary identity of a SiteRelatedSystemAssignment
    public siteRelatedSystemAssignmentUid : string;
    
  }
  
  /**
   * Contains results from calling 'GetSiteRelatedSystemAssignmentBySiteRelatedSystemAssignmentUid'.
   * Method: Loads a specific SiteRelatedSystemAssignment addressed by the given primary identifier. Returns null on failure, or if no record exists with the given identity.
   */
  export class GetSiteRelatedSystemAssignmentBySiteRelatedSystemAssignmentUidResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string = null;
    
    // Return-Value of 'GetSiteRelatedSystemAssignmentBySiteRelatedSystemAssignmentUid' (SiteRelatedSystemAssignment)
    public return : SiteRelatedSystemAssignment;
    
  }
  
  /**
   * Contains arguments for calling 'GetSiteRelatedSystemAssignments'.
   * Method: Loads SiteRelatedSystemAssignments.
   */
  export class GetSiteRelatedSystemAssignmentsRequest {
    
    // Optional Argument for 'GetSiteRelatedSystemAssignments' (number): Number of the page, which should be returned
    public page? : number = null;
    
    // Optional Argument for 'GetSiteRelatedSystemAssignments' (number): Max count of SiteRelatedSystemAssignments which should be returned
    public pageSize? : number = null;
    
  }
  
  /**
   * Contains results from calling 'GetSiteRelatedSystemAssignments'.
   * Method: Loads SiteRelatedSystemAssignments.
   */
  export class GetSiteRelatedSystemAssignmentsResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string = null;
    
    // Return-Value of 'GetSiteRelatedSystemAssignments' (SiteRelatedSystemAssignment[])
    public return : SiteRelatedSystemAssignment[];
    
  }
  
  /**
   * Contains arguments for calling 'SearchSiteRelatedSystemAssignments'.
   * Method: Loads SiteRelatedSystemAssignments where values matching to the given filterExpression
   */
  export class SearchSiteRelatedSystemAssignmentsRequest {
    
    // Required Argument for 'SearchSiteRelatedSystemAssignments' (string): a filter expression like '((FieldName1 == "ABC" &amp;&amp; FieldName2 &gt; 12) || FieldName2 != "")'
    public filterExpression : string;
    
    // Optional Argument for 'SearchSiteRelatedSystemAssignments' (string): one or more property names which are used as sort order (before pagination)
    public sortingExpression? : string;
    
    // Optional Argument for 'SearchSiteRelatedSystemAssignments' (number): Number of the page, which should be returned
    public page? : number = null;
    
    // Optional Argument for 'SearchSiteRelatedSystemAssignments' (number): Max count of SiteRelatedSystemAssignments which should be returned
    public pageSize? : number = null;
    
  }
  
  /**
   * Contains results from calling 'SearchSiteRelatedSystemAssignments'.
   * Method: Loads SiteRelatedSystemAssignments where values matching to the given filterExpression
   */
  export class SearchSiteRelatedSystemAssignmentsResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string = null;
    
    // Return-Value of 'SearchSiteRelatedSystemAssignments' (SiteRelatedSystemAssignment[])
    public return : SiteRelatedSystemAssignment[];
    
  }
  
  /**
   * Contains arguments for calling 'AddNewSiteRelatedSystemAssignment'.
   * Method: Adds a new SiteRelatedSystemAssignment and returns its primary identifier (or null on failure).
   */
  export class AddNewSiteRelatedSystemAssignmentRequest {
    
    // Required Argument for 'AddNewSiteRelatedSystemAssignment' (SiteRelatedSystemAssignment): SiteRelatedSystemAssignment containing the new values
    public siteRelatedSystemAssignment : SiteRelatedSystemAssignment;
    
  }
  
  /**
   * Contains results from calling 'AddNewSiteRelatedSystemAssignment'.
   * Method: Adds a new SiteRelatedSystemAssignment and returns its primary identifier (or null on failure).
   */
  export class AddNewSiteRelatedSystemAssignmentResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string = null;
    
    // Return-Value of 'AddNewSiteRelatedSystemAssignment' (Boolean)
    public return : boolean;
    
  }
  
  /**
   * Contains arguments for calling 'UpdateSiteRelatedSystemAssignment'.
   * Method: Updates all values (which are not "FixedAfterCreation") of the given SiteRelatedSystemAssignment addressed by the primary identifier fields within the given SiteRelatedSystemAssignment. Returns false on failure or if no target record was found, otherwise true.
   */
  export class UpdateSiteRelatedSystemAssignmentRequest {
    
    // Required Argument for 'UpdateSiteRelatedSystemAssignment' (SiteRelatedSystemAssignment): SiteRelatedSystemAssignment containing the new values (the primary identifier fields within the given SiteRelatedSystemAssignment will be used to address the target record)
    public siteRelatedSystemAssignment : SiteRelatedSystemAssignment;
    
  }
  
  /**
   * Contains results from calling 'UpdateSiteRelatedSystemAssignment'.
   * Method: Updates all values (which are not "FixedAfterCreation") of the given SiteRelatedSystemAssignment addressed by the primary identifier fields within the given SiteRelatedSystemAssignment. Returns false on failure or if no target record was found, otherwise true.
   */
  export class UpdateSiteRelatedSystemAssignmentResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string = null;
    
    // Return-Value of 'UpdateSiteRelatedSystemAssignment' (Boolean)
    public return : boolean;
    
  }
  
  /**
   * Contains arguments for calling 'UpdateSiteRelatedSystemAssignmentBySiteRelatedSystemAssignmentUid'.
   * Method: Updates all values (which are not "FixedAfterCreation") of the given SiteRelatedSystemAssignment addressed by the supplementary given primary identifier. Returns false on failure or if no target record was found, otherwise true.
   */
  export class UpdateSiteRelatedSystemAssignmentBySiteRelatedSystemAssignmentUidRequest {
    
    // Required Argument for 'UpdateSiteRelatedSystemAssignmentBySiteRelatedSystemAssignmentUid' (string): Represents the primary identity of a SiteRelatedSystemAssignment
    public siteRelatedSystemAssignmentUid : string;
    
    // Required Argument for 'UpdateSiteRelatedSystemAssignmentBySiteRelatedSystemAssignmentUid' (SiteRelatedSystemAssignment): SiteRelatedSystemAssignment containing the new values (the primary identifier fields within the given SiteRelatedSystemAssignment will be ignored)
    public siteRelatedSystemAssignment : SiteRelatedSystemAssignment;
    
  }
  
  /**
   * Contains results from calling 'UpdateSiteRelatedSystemAssignmentBySiteRelatedSystemAssignmentUid'.
   * Method: Updates all values (which are not "FixedAfterCreation") of the given SiteRelatedSystemAssignment addressed by the supplementary given primary identifier. Returns false on failure or if no target record was found, otherwise true.
   */
  export class UpdateSiteRelatedSystemAssignmentBySiteRelatedSystemAssignmentUidResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string = null;
    
    // Return-Value of 'UpdateSiteRelatedSystemAssignmentBySiteRelatedSystemAssignmentUid' (Boolean)
    public return : boolean;
    
  }
  
  /**
   * Contains arguments for calling 'DeleteSiteRelatedSystemAssignmentBySiteRelatedSystemAssignmentUid'.
   * Method: Deletes a specific SiteRelatedSystemAssignment addressed by the given primary identifier. Returns false on failure or if no target record was found, otherwise true.
   */
  export class DeleteSiteRelatedSystemAssignmentBySiteRelatedSystemAssignmentUidRequest {
    
    // Required Argument for 'DeleteSiteRelatedSystemAssignmentBySiteRelatedSystemAssignmentUid' (string): Represents the primary identity of a SiteRelatedSystemAssignment
    public siteRelatedSystemAssignmentUid : string;
    
  }
  
  /**
   * Contains results from calling 'DeleteSiteRelatedSystemAssignmentBySiteRelatedSystemAssignmentUid'.
   * Method: Deletes a specific SiteRelatedSystemAssignment addressed by the given primary identifier. Returns false on failure or if no target record was found, otherwise true.
   */
  export class DeleteSiteRelatedSystemAssignmentBySiteRelatedSystemAssignmentUidResponse {
    
    // This field contains error text equivalent to an Exception message! (note that only 'fault' XOR 'return' can have a value != null)
    public fault : string = null;
    
    // Return-Value of 'DeleteSiteRelatedSystemAssignmentBySiteRelatedSystemAssignmentUid' (Boolean)
    public return : boolean;
    
  }
  
}
