/* based on ORSCF VisitData Contract v1.7.0.11747 */

import * as Models from './models';

export interface IVdrApiInfoService {
  
  /**
   * returns the version of the ORSCF specification which is implemented by this API, (this can be used for backward compatibility within inhomogeneous infrastructures)
   */
  GetApiVersion() : string;
  
  /**
   * returns a list of API-features (there are several 'services' for different use cases, described by ORSCF) supported by this implementation. The following values are possible: 'VdrEventSubscription', 'VisitConsume', 'VisitSubmission', 'VisitHL7Export', 'VisitHL7Import', 'DataRecordingSubmission'
   */
  GetCapabilities() : string[];
  
  /**
   * returns a list of available capabilities ("API:VisitDataConsume") and/or data-scopes ("Study:9B2C3F48-2941-2F8F-4D35-7D117D5C6F72") which are permitted for the CURRENT ACCESSOR and gives information about its 'authState', which can be: 0=auth needed / 1=authenticated / -1=auth expired / -2=auth invalid/disabled
   *
   * @param authState
   */
  GetPermittedAuthScopes(authState : (out: number) => void) : string[];
  
  /**
   * OPTIONAL: If the authentication on the current service is mapped using tokens and should provide information about the source at this point, the login URL to be called up via browser (OAuth ['CIBA-Flow'](https://openid.net/specs/openid-client-initiated-backchannel-authentication-core-1_0.html)) is returned here.
   */
  GetOAuthTokenRequestUrl() : string;
  
}

export interface IVdrEventSubscriptionService {
  
  /**
   * Creates a subscription for changes which are affecting Visits. On success, a 'SubscriptionUid' will be returned and a call will be made to the given subscriberUrl + '/ConfirmAsSubscriber'. After the subscription has been confirmed, the requested events will be pushed to subscriberUrl + '/NoticeChangedVisits' (NOTICE: the receiving methods also are documented here, because this service itself can act as subscriber)
   *
   * @param subscriberUrl the root-url of the subscriber which needs to provide at least the methods
   '/ConfirmAsSubscriber' and '/NoticeChangedVisits'
   * @param filter if provided, the subscription will only publish events for
   records matching to the given filter
   */
  SubscribeForChangedVisits(subscriberUrl : string, filter : Models.VisitFilter) : string;
  
  /**
   * Receives notifications about changes which are affecting Visits. IMPORTANT: this method is dedicated to the usecase, when this service itself acts as a subscriber! So this can be called by an foreign service during the setup of a subscription, which was previously requested from here. The opposite case: any client subscribing to events from here, must provide its own http endpoint that has such a method!
   *
   * @param eventUid a UUID which identifies the current event message
   * @param eventSignature a SHA256 Hash of SubscriptionSecret + EventUid
   (in lower string representation, without '-' characters!)
   Sample: SHA256('ThEs3Cr3T'+'c997dfb1c445fea84afe995307713b59')
   = 'a320ef5b0f563e8dcb16d759961739977afc98b90628d9dc3be519fb20701490'
   * @param subscriptionUid a UUID which identifies the subscription for which this event is published
   * @param publisherUrl root-URL of the VDR-Service which is publishing this event
   * @param createdRecords
   * @param modifiedRecords
   * @param archivedRecords
   * @param terminateSubscription an array, which contains one element per changed visit
   */
  NoticeChangedVisits(eventUid : string, eventSignature : string, subscriptionUid : string, publisherUrl : string, createdRecords : Models.VisitMetaRecord[], modifiedRecords : Models.VisitMetaRecord[], archivedRecords : Models.VisitMetaRecord[], terminateSubscription : (out: boolean) => void) : void;
  
  /**
   * Confirms a Subscription. IMPORTANT: this method is dedicated to the usecase, when this service itself acts as a subscriber! So this can be called by an foreign service during the setup of a subscription, which was previously requested from here. The opposite case: any client subscribing to events from here, must provide its own http endpoint that has such a method!
   *
   * @param publisherUrl root-URL of the VDR-Service on which the subscription was requested
   * @param subscriptionUid the Uid of the subscription which should be confirmed
   * @param secret A secret which is generated by the subscriber and used to provide additional security.
   It will be required for the 'TerminateSubscription' method and it is used to generate
   SHA256 hashes for signing the delivered event messages.
   The secret should: have a minimum length of 32 characters.
   A null or empty string has the semantics that the subscriber refuses to confirm
   and cancels the subscription setup.
   */
  ConfirmAsSubscriber(publisherUrl : string, subscriptionUid : string, secret : (out: string) => void) : void;
  
  /**
   * Terminates a subscription (on publisher side) and returns a boolean, which indicates success.
   *
   * @param subscriptionUid the Uid of the subscription which should be terminated
   * @param secret the (same) secret, which was given by the subscriber during the subscription setup
   */
  TerminateSubscription(subscriptionUid : string, secret : string) : boolean;
  
  /**
   * Returns an array of subscriptionUid's. This method helps subscribers to evaluate whether current subscriptions are still active.
   *
   * @param subscriberUrl
   * @param secret the (same) secret, which was given by the subscriber during the subscription setup
   */
  GetSubsriptionsBySubscriberUrl(subscriberUrl : string, secret : string) : string[];
  
}

export interface IDataRecordingSubmissionService {
  
  /**
   * ImportDataRecordings
   *
   * @param dataRecordings
   * @param createdDataRecordingUids
   * @param updatedDataRecordingUids
   */
  ImportDataRecordings(dataRecordings : Models.DataRecordingStructure[], createdDataRecordingUids : (out: string[]) => void, updatedDataRecordingUids : (out: string[]) => void) : void;
  
}

export interface IVisitConsumeService {
  
  /**
   * Searches Visits by a given 'filter' (if provided), sorts the results by the given 'sortingField' (if provided) and returns an array of VisitUids for the matching records.
   *
   * @param result
   * @param sortingField A fieldname, which should be used to sort the result (can also be a 'CustomField').
   If not provided, the result will be sorted by the creation date of the records
   * @param sortDescending toggles the sorting direction
   * @param filter values by field name (can also be a 'CustomField') which will used as AND-linked filter
   * @param includeArchivedRecords includes archived records in the result
   * @param limitResults a value greather than zero will represent a maximum count of results, that sould be returned
   */
  SearchVisits(result : (out: Models.VisitMetaRecord[]) => void, sortingField : string, sortDescending : boolean, filter : Models.VisitFilter, includeArchivedRecords : boolean, limitResults : number) : void;
  
  /**
   * Searches Visits which have been modified after(or at) the given 'minTimestampUtc', matching to the given 'filter' (if provided). The result is sorted descenting by the timestamp of the modification (latest first) and will include archived records.
   *
   * @param minTimestampUtc start of the timespan to search (as UNIX-Timestamp)
   * @param latestTimestampUtc the exact timestamp of the search (as UNIX-Timestamp)
   * @param createdRecords
   * @param modifiedRecords
   * @param archivedRecords
   * @param filter values by field name (can also be a 'CustomField') which will used as AND-linked filter
   */
  SearchChangedVisits(minTimestampUtc : number, latestTimestampUtc : (out: number) => void, createdRecords : (out: Models.VisitMetaRecord[]) => void, modifiedRecords : (out: Models.VisitMetaRecord[]) => void, archivedRecords : (out: Models.VisitMetaRecord[]) => void, filter : Models.VisitFilter) : void;
  
  /**
   * GetCustomFieldDescriptorsForVisit
   *
   * @param languagePref Preferred language for the 'DisplayLabel' and 'InputDescription'
   fields of the returned descriptors. The default is 'EN'.
   */
  GetCustomFieldDescriptorsForVisit(languagePref : string) : Models.CustomFieldDescriptor[];
  
  /**
   * Checks the existence of 'Visits' for a given list of visitUids
   *
   * @param visitUids
   * @param unavailableVisitUids
   * @param availableVisitUids
   */
  CheckVisitExisitence(visitUids : string[], unavailableVisitUids : (out: string[]) => void, availableVisitUids : (out: string[]) => void) : void;
  
  /**
   * loads the requested visits and returns lightweight json objects (without childs), which are optimized to be displayed as table (the most common UI use case). This models containig a combination of: essential fieds from the record, calculated fields (numbers of child records), custom fields (choosen by the service)
   *
   * @param visitUids
   * @param unavailableVisitUids
   * @param result
   */
  GetVisitFields(visitUids : string[], unavailableVisitUids : (out: string[]) => void, result : (out: Models.VisitFields[]) => void) : void;
  
  /**
   * exports full 'VisitStructures'
   *
   * @param visitUids
   * @param unavailableVisitUids
   * @param result
   */
  ExportVisits(visitUids : string[], unavailableVisitUids : (out: string[]) => void, result : (out: Models.VisitStructure[]) => void) : void;
  
}

export interface IVisitHL7ExportService {
  
  /**
   * Exports a structure containing HL7/FHIR-Ressources (JSON only) and the essential fields which are required to qualify a ORSCF record.
   *
   * @param visitUid
   * @param visitFhirRessources
   */
  ExportVisitFhirRessources(visitUid : string, visitFhirRessources : (out: Models.VisitFhirRessourceContainer[]) => void) : boolean;
  
}

export interface IVisitHL7ImportService {
  
  /**
   * Exports a structure containing HL7/FHIR-Ressources (JSON only) and the essential fields which are required to qualify a ORSCF record.
   *
   * @param visitFhirRessources
   * @param createdVisitUids
   * @param updatedVisitUids
   */
  ImportVisitFhirRessources(visitFhirRessources : Models.VisitFhirRessourceContainer[], createdVisitUids : (out: string[]) => void, updatedVisitUids : (out: string[]) => void) : void;
  
}

export interface IVisitSubmissionService {
  
  /**
   * ArchiveVisits
   *
   * @param visitUids
   * @param archivedVisitUids also including the Uids of already archived records
   */
  ArchiveVisits(visitUids : string[], archivedVisitUids : (out: string[]) => void) : void;
  
  /**
   * UnarchiveVisits
   *
   * @param visitUids
   * @param unarchivedVisitUids
   */
  UnarchiveVisits(visitUids : string[], unarchivedVisitUids : (out: string[]) => void) : void;
  
  /**
   * ApplyVisitMutations
   *
   * @param mutationsByVisitUid
   * @param updatedVisitUids
   */
  ApplyVisitMutations(mutationsByVisitUid : Object, updatedVisitUids : (out: string[]) => void) : void;
  
  /**
   * ApplyVisitBatchMutation
   *
   * @param visitUids
   * @param mutation
   * @param updatedVisitUids
   */
  ApplyVisitBatchMutation(visitUids : string[], mutation : Models.BatchableVisitMutation, updatedVisitUids : (out: string[]) => void) : void;
  
  /**
   * ImportVisits
   *
   * @param visits
   * @param createdVisitUids
   * @param updatedVisitUids
   */
  ImportVisits(visits : Models.VisitStructure[], createdVisitUids : (out: string[]) => void, updatedVisitUids : (out: string[]) => void) : void;
  
}
