".\kGen\kGEN.exe" "generate-models.BDR.json" > "..\Contracts\BDR-Contract\models.ts"
".\kGen\kGEN.exe" "generate-models.IMS.json" > "..\Contracts\IMS-Contract\models.ts"
".\kGen\kGEN.exe" "generate-models.SDR.json" > "..\Contracts\SDR-Contract\models.ts"
".\kGen\kGEN.exe" "generate-models.SMS.json" > "..\Contracts\SMS-Contract\models.ts"
".\kGen\kGEN.exe" "generate-models.VDR.json" > "..\Contracts\VDR-Contract\models.ts"
".\kGen\kGEN.exe" "generate-models.WDR.json" > "..\Contracts\WDR-Contract\models.ts"
