/* based on ORSCF SubjectData Contract v0.1.0.0 */

import MedicalResearch.SubjectData.Model;

namespace MedicalResearch.SubjectData.StoreAccess {
  
  /**
   * entity, which relates to <see href="https://www.hl7.org/fhir/researchsubject.html">HL7.ResearchSubject</see>
   */
  public class Subject {
    
    /**
     * An <see href="https://de.wikipedia.org/wiki/Universally_Unique_Identifier">Universally Unique Identifier</see> which can be generated by any origin system and is used to address this ORSCF conform data record in decentralized environments. Note that this Identity must not be changed any more!
     */
    public subjectUid : string { get; set; }
    
    public actualSiteIdentifier : string { get; set; }
    
    public enrollingSiteIdentifier : string { get; set; }
    
    /**
     * *this field is optional
     */
    public enrollmentDate : date? { get; set; }
    
    /**
     * *this field is optional
     */
    public terminationDate : date? { get; set; }
    
    /**
     * *this field is optional (use null as value)
     */
    public terminatedReason : string { get; set; }
    
    /**
     * *this field is optional (use null as value)
     */
    public subjectIdentifier : string { get; set; }
    
    /**
     * AS DECLARED BY <see href="https://www.hl7.org/fhir/valueset-research-subject-status.html">HL7.ResearchSubjectStatus</see>: candidate | eligible | follow-up | ineligible | not-registered | off-study | on-study | on-study-intervention | on-study-observation | pending-on-study | potential-candidate | screening | withdrawn
     */
    public status : string { get; set; }
    
    public researchStudyUid : string { get; set; }
    
  }
  
  public class SubjectSiteAssignment {
    
    /**
     * An <see href="https://de.wikipedia.org/wiki/Universally_Unique_Identifier">Universally Unique Identifier</see> which can be generated by any origin system and is used to address this ORSCF conform data record in decentralized environments. Note that this Identity must not be changed any more!
     */
    public subjectSiteAssignmentUid : string { get; set; }
    
    public validFrom : date { get; set; }
    
    /**
     * <see href="https://de.wikipedia.org/wiki/Universally_Unique_Identifier">Universally Unique Identifier</see> of the target Site
     */
    public siteUid : string { get; set; }
    
    /**
     * <see href="https://de.wikipedia.org/wiki/Universally_Unique_Identifier">Universally Unique Identifier</see> of the target Subject
     */
    public subjectUid : string { get; set; }
    
    /**
     * This can be the ID ('surrogate-key') of the Partient record within a site specific patient management system. This MUST NOT be any natural key or plain readable name which exposes the identity of the patient! *this field is optional (use null as value)
     */
    public siteRelatedPatientIdentifier : string { get; set; }
    
    /**
     * *this field is optional
     */
    public byInvolvedPersonUid : string? { get; set; }
    
  }
  
}
