/* based on ORSCF SubjectData Contract v1.7.0.0 */


/**
 * entity, which relates to [HL7.ResearchSubject](https://www.hl7.org/fhir/researchsubject.html)
 */
export class Subject {
  
  /**
   * An [Universally Unique Identifier](https://de.wikipedia.org/wiki/Universally_Unique_Identifier) which can be generated by any origin system and is used to address this ORSCF conform data record in decentralized environments. Note that this Identity must not be changed any more!
   */
  public subjectUid : string;
  
  public actualSiteIdentifier : string;
  
  public enrollingSiteIdentifier : string;
  
  /**
   * *this field is optional
   */
  public enrollmentDate : Date;
  
  /**
   * *this field is optional
   */
  public terminationDate : Date;
  
  /**
   * *this field is optional (use null as value)
   */
  public terminatedReason : string;
  
  /**
   * *this field is optional (use null as value)
   */
  public subjectIdentifier : string;
  
  /**
   * AS DECLARED BY [HL7.ResearchSubjectStatus](https://www.hl7.org/fhir/valueset-research-subject-status.html): candidate | eligible | follow-up | ineligible | not-registered | off-study | on-study | on-study-intervention | on-study-observation | pending-on-study | potential-candidate | screening | withdrawn
   */
  public status : string;
  
  public researchStudyUid : string;
  
}

export class SubjectSiteAssignment {
  
  /**
   * An [Universally Unique Identifier](https://de.wikipedia.org/wiki/Universally_Unique_Identifier) which can be generated by any origin system and is used to address this ORSCF conform data record in decentralized environments. Note that this Identity must not be changed any more!
   */
  public subjectSiteAssignmentUid : string;
  
  public validFrom : Date;
  
  /**
   * [Universally Unique Identifier](https://de.wikipedia.org/wiki/Universally_Unique_Identifier) of the target Site
   */
  public siteUid : string;
  
  /**
   * [Universally Unique Identifier](https://de.wikipedia.org/wiki/Universally_Unique_Identifier) of the target Subject
   */
  public subjectUid : string;
  
  /**
   * This can be the ID ('surrogate-key') of the Partient record within a site specific patient management system. This MUST NOT be any natural key or plain readable name which exposes the identity of the patient! *this field is optional (use null as value)
   */
  public siteRelatedPatientIdentifier : string;
  
  /**
   * *this field is optional
   */
  public byInvolvedPersonUid : string;
  
}
