/* based on ORSCF SubjectData Contract v1.7.0.0 */

import MedicalResearch.SubjectData.Model;

namespace MedicalResearch.SubjectData.StoreAccess {
  
  export interface ISubjects {
    
    /**
     * Loads a specific Subject addressed by the given primary identifier. Returns null on failure, or if no record exists with the given identity.
     *
     * @param subjectUid An <see href="https://de.wikipedia.org/wiki/Universally_Unique_Identifier">Universally Unique Identifier</see> which can be generated by any origin system and is used to address this ORSCF conform data record in decentralized environments. Note that this Identity must not be changed any more!
     */
    GetSubjectBySubjectUid(subjectUid : string) : GetSubjectBySubjectUidResponse;
    
    /**
     * Loads Subjects.
     *
     * @param page Number of the page, which should be returned
     * @param pageSize Max count of Subjects which should be returned
     */
    GetSubjects(page : number, pageSize : number) : GetSubjectsResponse;
    
    /**
     * Loads Subjects where values matching to the given filterExpression
     *
     * @param filterExpression a filter expression like '((FieldName1 == "ABC" &amp;&amp; FieldName2 &gt; 12) || FieldName2 != "")'
     * @param sortingExpression one or more property names which are used as sort order (before pagination)
     * @param page Number of the page, which should be returned
     * @param pageSize Max count of Subjects which should be returned
     */
    SearchSubjects(filterExpression : string, sortingExpression : string, page : number, pageSize : number) : SearchSubjectsResponse;
    
    /**
     * Adds a new Subject and returns its primary identifier (or null on failure).
     *
     * @param subject Subject containing the new values
     */
    AddNewSubject(subject : Subject) : AddNewSubjectResponse;
    
    /**
     * Updates all values (which are not "FixedAfterCreation") of the given Subject addressed by the primary identifier fields within the given Subject. Returns false on failure or if no target record was found, otherwise true.
     *
     * @param subject Subject containing the new values (the primary identifier fields within the given Subject will be used to address the target record)
     */
    UpdateSubject(subject : Subject) : UpdateSubjectResponse;
    
    /**
     * Updates all values (which are not "FixedAfterCreation") of the given Subject addressed by the supplementary given primary identifier. Returns false on failure or if no target record was found, otherwise true.
     *
     * @param subjectUid An <see href="https://de.wikipedia.org/wiki/Universally_Unique_Identifier">Universally Unique Identifier</see> which can be generated by any origin system and is used to address this ORSCF conform data record in decentralized environments. Note that this Identity must not be changed any more!
     * @param subject Subject containing the new values (the primary identifier fields within the given Subject will be ignored)
     */
    UpdateSubjectBySubjectUid(subjectUid : string, subject : Subject) : UpdateSubjectBySubjectUidResponse;
    
    /**
     * Deletes a specific Subject addressed by the given primary identifier. Returns false on failure or if no target record was found, otherwise true.
     *
     * @param subjectUid An <see href="https://de.wikipedia.org/wiki/Universally_Unique_Identifier">Universally Unique Identifier</see> which can be generated by any origin system and is used to address this ORSCF conform data record in decentralized environments. Note that this Identity must not be changed any more!
     */
    DeleteSubjectBySubjectUid(subjectUid : string) : DeleteSubjectBySubjectUidResponse;
    
  }
  
  export interface ISubjectSiteAssignments {
    
    /**
     * Loads a specific SubjectSiteAssignment addressed by the given primary identifier. Returns null on failure, or if no record exists with the given identity.
     *
     * @param subjectSiteAssignmentUid An <see href="https://de.wikipedia.org/wiki/Universally_Unique_Identifier">Universally Unique Identifier</see> which can be generated by any origin system and is used to address this ORSCF conform data record in decentralized environments. Note that this Identity must not be changed any more!
     */
    GetSubjectSiteAssignmentBySubjectSiteAssignmentUid(subjectSiteAssignmentUid : string) : GetSubjectSiteAssignmentBySubjectSiteAssignmentUidResponse;
    
    /**
     * Loads SubjectSiteAssignments.
     *
     * @param page Number of the page, which should be returned
     * @param pageSize Max count of SubjectSiteAssignments which should be returned
     */
    GetSubjectSiteAssignments(page : number, pageSize : number) : GetSubjectSiteAssignmentsResponse;
    
    /**
     * Loads SubjectSiteAssignments where values matching to the given filterExpression
     *
     * @param filterExpression a filter expression like '((FieldName1 == "ABC" &amp;&amp; FieldName2 &gt; 12) || FieldName2 != "")'
     * @param sortingExpression one or more property names which are used as sort order (before pagination)
     * @param page Number of the page, which should be returned
     * @param pageSize Max count of SubjectSiteAssignments which should be returned
     */
    SearchSubjectSiteAssignments(filterExpression : string, sortingExpression : string, page : number, pageSize : number) : SearchSubjectSiteAssignmentsResponse;
    
    /**
     * Adds a new SubjectSiteAssignment and returns its primary identifier (or null on failure).
     *
     * @param subjectSiteAssignment SubjectSiteAssignment containing the new values
     */
    AddNewSubjectSiteAssignment(subjectSiteAssignment : SubjectSiteAssignment) : AddNewSubjectSiteAssignmentResponse;
    
    /**
     * Updates all values (which are not "FixedAfterCreation") of the given SubjectSiteAssignment addressed by the primary identifier fields within the given SubjectSiteAssignment. Returns false on failure or if no target record was found, otherwise true.
     *
     * @param subjectSiteAssignment SubjectSiteAssignment containing the new values (the primary identifier fields within the given SubjectSiteAssignment will be used to address the target record)
     */
    UpdateSubjectSiteAssignment(subjectSiteAssignment : SubjectSiteAssignment) : UpdateSubjectSiteAssignmentResponse;
    
    /**
     * Updates all values (which are not "FixedAfterCreation") of the given SubjectSiteAssignment addressed by the supplementary given primary identifier. Returns false on failure or if no target record was found, otherwise true.
     *
     * @param subjectSiteAssignmentUid An <see href="https://de.wikipedia.org/wiki/Universally_Unique_Identifier">Universally Unique Identifier</see> which can be generated by any origin system and is used to address this ORSCF conform data record in decentralized environments. Note that this Identity must not be changed any more!
     * @param subjectSiteAssignment SubjectSiteAssignment containing the new values (the primary identifier fields within the given SubjectSiteAssignment will be ignored)
     */
    UpdateSubjectSiteAssignmentBySubjectSiteAssignmentUid(subjectSiteAssignmentUid : string, subjectSiteAssignment : SubjectSiteAssignment) : UpdateSubjectSiteAssignmentBySubjectSiteAssignmentUidResponse;
    
    /**
     * Deletes a specific SubjectSiteAssignment addressed by the given primary identifier. Returns false on failure or if no target record was found, otherwise true.
     *
     * @param subjectSiteAssignmentUid An <see href="https://de.wikipedia.org/wiki/Universally_Unique_Identifier">Universally Unique Identifier</see> which can be generated by any origin system and is used to address this ORSCF conform data record in decentralized environments. Note that this Identity must not be changed any more!
     */
    DeleteSubjectSiteAssignmentBySubjectSiteAssignmentUid(subjectSiteAssignmentUid : string) : DeleteSubjectSiteAssignmentBySubjectSiteAssignmentUidResponse;
    
  }
  
}
